Chia-Network/chia_rs

src/gen/conditions.rs

checking that extra arguments are ignored

additional test for conditions

---

src/gen/coin_id.rs
src/gen/conditions.rs
src/streamable/bytes.rs
src/streamable/ser.rs

to clean up usage of BytesImpl

replace custom slice() with AsRef and Deref traits

---

.github/workflows/build-test.yml
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/parse-cond-args.rs
fuzz/fuzz_targets/parse-conditions.rs
fuzz/fuzz_targets/parse-spend.rs
fuzz/fuzz_targets/puzzle-coin-solution.rs
src/fuzzing_utils.rs
src/gen/conditions.rs
src/gen/get_puzzle_and_solution.rs
src/lib.rs

this patch adds fuzz targets to parsing and checking conditions from a block generator, as well as the recently added `get_puzzle_and_solution_for_coin()`

add fuzzers

---

Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

For a release that actually publishes correctly

Version bump

---

src/gen/conditions.rs
tests/test_streamable.py
wheel/src/api.rs
wheel/src/run_generator.rs

where one flag indicates eligible for dedup

instead of using a bool field, expose a flags field

---

.github/workflows/build-test.yml

Compare and contrast with https://github.com/Chia-Network/chia_rs/pull/93.

MACOSX_DEPLOYMENT_TARGET: 10.14

---

src/gen/condition_sanitizers.rs
src/gen/conditions.rs
src/gen/sanitize_int.rs
src/gen/validation_error.rs

and make CREATE_COIN fail with that if it specifies a too large amount

Introduce AmountExceedsMaximum error code

---

src/fuzzing_utils.rs

importantly not recursive, to avoid spurious stack-overflows when fuzzing

make the fuzzing utility make_tree() more efficient

---

src/gen/conditions.rs

factor out the check that conditions have the right number of arguments into a function, to reduce duplicate code

STRICT_ARGS_COUNT refactor

---

src/gen/validation_error.rs

this was a typo in a recent PR

fix typo in validation_error

---

chia-tools/graph.gnuplot
chia-tools/parse-analyze-chain.py
chia-tools/src/bin/analyze-chain.rs

This extends the chain analysis with block timestamps

log block timestamps and delta time

---

Cargo.toml
chia-protocol/Cargo.toml
chia-tools/Cargo.toml
clvm-utils/Cargo.toml
clvm-utils/fuzz/Cargo.toml
fuzz/Cargo.toml
wheel/Cargo.toml

This includes the updated `softfork` behavior

bump clvmr version to 0.2.4

---

clvm-utils/src/uncurry.rs

use of `Node` is being phased out.
This also makes `unwrap3` a general function that (at some point) may be moved out.

cleanup uncurry.rs and drop use of Node

---

src/gen/test_generators.rs

the `print_diff()` function prints the complete output, not just the difference. This update makes a test failure just print 3 lines of context around the differences. It makes it a lot easier to interpret test failures

improve ouput from test_generators test. more concise diff

---

.github/workflows/build-test.yml

They test resource usage, not correctness

don't run stress tests under coverage instrumentation

---

chia-tools/src/bin/test-block-generators.rs

to support re-serializing generators with back-references. This allows validating that the result is identical after re-serializing the generator, like this:
```
cargo run --release --bin test-block-generators -- --file ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite --test-backrefs --validate
```

extend the test-block-generators tool

---

fuzz/Cargo.toml
fuzz/fuzz_targets/run-generator.rs

It's running in CI here:
https://github.com/Chia-Network/chia_rs/actions/runs/5437652803/jobs/9888364343?pr=204#step:5:1452

add fuzzer for run_block_generator() and run_block_generator2()

---

.github/workflows/build-test.yml

Changed MACOSX_DEPLOYMENT_TARGET to 11
Remove python 3.7

Change macOS target to macOS 11 and remove python 3.7

---

chia-bls/src/secret_key.rs

This makes this function easier to reuse

to_lamport_pk() should be a free function

---

chia-bls/src/public_key.rs
chia-bls/src/signature.rs

Specifically the case of infinity

add unit tests for is_valid() on PublicKey and Signature

---

chia-bls/Cargo.toml
chia-bls/src/public_key.rs
chia-bls/src/secret_key.rs
chia-bls/src/signature.rs

implement a few handy traits for `PublicKey` and `Signature`.
* `AddAssign`
* `Add`
* `Hash`
* `Debug`

BLS traits

---

.github/workflows/benchmark.yml

until we have the runners back"
This reverts commit 378aeec46e6a8e6ae01064d3d89e8abcef5f17e3.
I also added one more commit, on top of the revert commit.

Revert "temporarily disable benchmark runs on CI

---

chia-protocol/src/bytes.rs

if it sees an atom of the wrong size

fix Bytes32::from_clvm() to not panic

---

Cargo.lock
chia-protocol/src/program.rs
chia-tools/Cargo.toml
chia-tools/src/bin/gen-corpus.rs
chia-tools/src/lib.rs
chia-tools/src/visit_spends.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/run-puzzle.rs
src/gen/run_block_generator.rs

along with a tool to generate the corpus. picking all spends with a unique inner-puzzle from a blockchain database

add fuzzer for run_puzzle()

---

src/gen/conditions.rs
wheel/Cargo.toml
wheel/src/api.rs

both release 0.2.10 and 0.2.11 introduced bug fixes on top of the previous release tag.
This PR brings those fixes back into the `main` branch.

Land hot-fixes

---

chia-protocol/src/classgroup.rs
wheel/chia_rs.pyi
wheel/generate_type_stubs.py

This is to match the corresponding types in `chia-blockchain`.
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/blockchain_format/classgroup.py#L21

fixup member functions for ClassgroupElement

---

chia-protocol/fuzz/fuzz_targets/streamable.rs
chia-protocol/src/fullblock.rs
chia-protocol/src/unfinished_block.rs
wheel/chia_rs.pyi
wheel/generate_type_stubs.py

The member functions added to `FullBlock` are supposed to be identical to:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/full_block.py#L36-L83
The member functions added to `UnfinishedBlock` are supposed to be identical to:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/unfinished_block.py#L32-L45

add member functions to FullBlock and UnfinishedBlock

---

chia-protocol/src/reward_chain_block.rs
wheel/chia_rs.pyi
wheel/generate_type_stubs.py

this is the chia-blockchain counterpart:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/blockchain_format/reward_chain_block.py#L46-L56

RewardChainBlock get_unfinished()

---

.github/workflows/build-crate-and-npm.yml

publish `clvm-derive` and fix the publish order of crates.

fix github workflow publishing crates

---

Cargo.lock
chia-client/src/error.rs
chia-client/src/peer.rs

Some small improvements to improve readability

Refactor client code

---

chia-protocol/src/header_block.rs
wheel/chia_rs.pyi
wheel/generate_type_stubs.py
wheel/src/api.rs

These are the chia-blockchain counterparts:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/header_block.py#L31-L65

add member functions to HeaderBlock

---

.gitignore

Recently JetBrains released "RustRover" as the new IDE for Rust developing.

Ignore JetBrains .idea/ directory

---

Cargo.lock

Bump zerocopy

---

Cargo.lock
Cargo.toml
chia-protocol/Cargo.toml
chia-protocol/fuzz/Cargo.toml
chia-protocol/src/program.rs
chia-tools/Cargo.toml
chia-wallet/Cargo.toml
chia-wallet/fuzz/Cargo.toml
clvm-utils/Cargo.toml
clvm-utils/fuzz/Cargo.toml
fuzz/Cargo.toml
wheel/Cargo.toml

and update Program to support both trusted and untrusted parsing

bump clvmr dependency to 0.3.3

---

.github/workflows/build-test.yml
Cargo.lock
Cargo.toml
chia-bls/Cargo.toml
wheel/Cargo.toml

Using latest BLST building with clang to workaround AMD K10 issues with portable

build with clang-cl on windows to get proper portable SHA256

---

.github/workflows/build-riscv64.yml

Make wheels for supported python versions and added upload step to chia pypi for riscb

Add python versions and upload to chia pypi for riscv

---

clvm-derive/src/helpers.rs

by using the let-else construct.
This is best reviewed ignoring whitespace changes, since there's a change in indentation.

small simplification to clvm-derive/sec/helpers.rs

---

chia-traits/src/int.rs

running the coin selection test from `chia-blockchain`.
with this patch:
```
246.12s call     tests/wallet/test_wallet_trade_store.py::test_large_trade_record_query
190.06s call     tests/wallet/test_transaction_store.py::test_large_tx_record_query
47.61s call     tests/wallet/test_coin_selection.py::TestCoinSelection::test_knapsack_coin_selection
```
with chia_rs 0.4.0:
```
241.49s call     tests/wallet/test_wallet_trade_store.py::test_large_trade_record_query
185.95s call     tests/wallet/test_transaction_store.py::test_large_tx_record_query
14.47s call     tests/wallet/test_coin_selection.py::TestCoinSelection::test_knapsack_coin_selection
```

optimize conversions to native-python uint32 etc. primitive integer types

---

.github/workflows/build-riscv64.yml

Add id-token: write permission so GitHub will issue a JWT

---

Cargo.lock
chia-protocol/src/program.rs
tests/test_program.py
wheel/src/adapt_response.rs
wheel/src/api.rs
wheel/src/run_program.rs

back-port of https://github.com/Chia-Network/chia_rs/pull/402 onto the current stable release branch for a hot-fix release 0.4.1

Hotfix program run

---

Cargo.lock
Cargo.toml
chia-client/Cargo.toml
chia-protocol/Cargo.toml
chia-tools/Cargo.toml
chia-wallet/Cargo.toml
wheel/Cargo.toml

bump version

---

crates/chia-consensus/src/gen/condition_sanitizers.rs
crates/chia-consensus/src/gen/conditions.rs

Any combination of message mode is now allowed in mempool mode as well

relax mempool mode for message conditions

---

crates/chia-protocol/src/lib.rs
wheel/generate_type_stubs.py
wheel/python/chia_rs/chia_rs.pyi
wheel/src/api.rs

expose the type in the python bindings and amend the type-stub.

Unfinished header block python binding

---

crates/chia-puzzles/src/puzzles/offer.rs

No constructors or helper methods, but I can add those later.

Add settlement payments (offer) types

---

.github/workflows/build-test.yml

Manylinux 2_28 and always pull the build image

---

.github/workflows/audit-check.yml
.github/workflows/benchmark.yml
.github/workflows/build-crate-and-npm.yml
.github/workflows/build-test.yml
.github/workflows/prettier.yml
.gitignore
.pre-commit-config.yaml
.prettierrc
README.md
generator-tests/README.md
package-lock.json
package.json
prettierrc.yaml
wasm/README.md
wheel/README.md

Review without whitespace enabled

CHIA-920: Add Prettier to CI and pre-commit

---

crates/chia-consensus/src/gen/get_puzzle_and_solution.rs
tests/test_get_puzzle_and_solution.py

Adds a test for the python binding as well as the underlying rust implementation

Test `get_puzzle_and_solution_for_coin()`

---

wheel/python/chia_rs/sized_bytes.py

actually add the zeros attributes

---

crates/chia-consensus/src/spendbundle_validation.rs

A straightforward variable rename

Remove references to `NPCResult`

---

crates/chia-tools/src/bin/test-block-generators.rs

This tool is useful when validating changes to `run_block_generator()` against all blocks on mainnet or testnet11.
For example, validating that signature validation passes on all blocks.
The old flag `test-backrefs` no longer worked and was removed.
The assert `args.validate && !args.mempool` was incorrect and was removed.
The option `--validate` did not work past the hard fork height, which was fixed. It was also renamed to `--original-generator`.
A new option `--hard-fork-height` was added to support testnet databases.

clean up test-block-generators to be more useful for future work

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzles/Cargo.toml
crates/chia-puzzles/fuzz/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wheel/Cargo.toml

automated by `cargo ws version --all --no-git-commit`

bump chia_rs version to 0.15.0

---

wheel/pyproject.toml

Source hash: a404233742a85d8c84d28dd507e364a11bb5400d

catchup: into long_lived/initial_datalayer from main  @ a404233742a85d8c84d28dd507e364a11bb5400d

---

.github/workflows/build-wheels.yml
Cargo.lock
Cargo.toml
crates/chia-consensus/src/gen/solution_generator.rs

Reverts Chia-Network/chia_rs#845
seeing many segfaults on shutdown with this.
https://github.com/Chia-Network/chia_rs/pull/848

Revert "bump clvm_rs dependency"

---

crates/chia-datalayer/Cargo.toml

pointed out by @rigidity in https://github.com/Chia-Network/chia_rs/pull/872/files

correct datalayer py-bindings settings for chia-protocol

---

.github/workflows/audit-check.yml
.github/workflows/build-wheels.yml

to address https://github.com/Chia-Network/chia_rs/actions/runs/12853006151/job/35845770839?pr=869
as well as this: https://github.com/Chia-Network/chia_rs/actions/runs/12857779197/job/35846038279

install cargo audit

---

crates/chia-tools/src/bin/test-block-generators.rs

the switch re-compresses every block with the `Serializer` class and run it, to ensure they are still valid

add switch to test-block-generators to re-compress blocks

---

Cargo.lock
Cargo.toml
README.md
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

and update README with instructions

bump version 0.19.0

---

.github/workflows/benchmark.yml
Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-consensus/src/gen/conditions.rs
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
package-lock.json
package.json
wasm/Cargo.toml
wheel/Cargo.toml

Source hash: 4d479dd3e971340db7d0aa8acacb856487ea59eb

catchup: into long_lived/initial_datalayer from main  @ 4d479dd3e971340db7d0aa8acacb856487ea59eb

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

prepare for cutting a new release

bump version to 0.21.2

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

Source hash: 4eb3cf0e31658e8831aece561b02099dafc2790b

catchup: into long_lived/initial_datalayer from main  @ 4eb3cf0e31658e8831aece561b02099dafc2790b

---

crates/chia-consensus/src/spendbundle_conditions.rs
crates/chia-consensus/src/spendbundle_validation.rs

to ensure the puzzle reveal matches the puzzle hash of the coin being spent

CHIA-2826 validate puzzle hash in run_spendbundle()

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

this PR was made by:
```
cargo ws version --force "**" --all --no-git-commit
```

bump version to 0.24.0

---

crates/chia-datalayer/src/lib.rs
crates/chia-datalayer/src/merkle.rs
crates/chia-datalayer/src/merkle/dot.rs
crates/chia-datalayer/src/merkle/iterators.rs

extract datalayer iterators to separate file

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

done by executing:
```
cargo ws version --force "**" --all --no-git-commit
```

bump version to 0.27.0

---

Cargo.lock
Cargo.toml
crates/chia-consensus/src/build_compressed_block.rs
crates/chia-consensus/src/error.rs
crates/chia-consensus/src/solution_generator.rs
crates/chia-consensus/src/validation_error.rs
crates/chia-protocol/src/program.rs
crates/chia-protocol/src/spend_bundle.rs
crates/chia-tools/src/bin/benchmark-condition-costs.rs
crates/chia-tools/src/bin/run-spend.rs
crates/clvm-utils/src/tree_hash.rs
wheel/src/api.rs
wheel/src/error.rs
wheel/src/lib.rs
wheel/src/run_program.rs

Update to clvmrs 0.16.0 with new error codes

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-fuzzing/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

bump to 0.28.1

---

Cargo.lock
Cargo.toml
crates/chia-bls/Cargo.toml
crates/chia-bls/fuzz/Cargo.toml
crates/chia-client/Cargo.toml
crates/chia-consensus/Cargo.toml
crates/chia-consensus/fuzz/Cargo.toml
crates/chia-fuzzing/Cargo.toml
crates/chia-protocol/Cargo.toml
crates/chia-protocol/fuzz/Cargo.toml
crates/chia-puzzle-types/Cargo.toml
crates/chia-puzzle-types/fuzz/Cargo.toml
crates/chia-secp/Cargo.toml
crates/chia-serde/Cargo.toml
crates/chia-sha2/Cargo.toml
crates/chia-ssl/Cargo.toml
crates/chia-tools/Cargo.toml
crates/chia-traits/Cargo.toml
crates/chia_py_streamable_macro/Cargo.toml
crates/chia_streamable_macro/Cargo.toml
crates/clvm-derive/Cargo.toml
crates/clvm-traits/Cargo.toml
crates/clvm-traits/fuzz/Cargo.toml
crates/clvm-utils/Cargo.toml
crates/clvm-utils/fuzz/Cargo.toml
wasm/Cargo.toml
wheel/Cargo.toml

Source hash: b5b4926b59411b4f68c373b04ba448a94ded0f79

catchup: into long_lived/initial_datalayer from main  @ b5b4926b59411b4f68c373b04ba448a94ded0f79

---

crates/chia-datalayer/src/merkle/blob.rs
crates/chia-datalayer/src/merkle/deltas.rs

last i checked pyo3 did not support this, now it does

less manual path extraction
