src/gen/conditions.rs, src/gen/flags.rs, wheel/src/api.rs
probably best reviewed with whitespace ignored.
=> in mempool mode, also check the number of arguments to conditions

.github/workflows/benchmark.yml, tests/run-programs.py, tests/run.py, wheel/src/api.rs, wheel/src/lib.rs, wheel/src/run_program.rs
This makes it possible for chia-blockchain to only depend on the chia_rs module.
There's some duplicated code with `clvm_rs/wheel` here, I can't think of a way to avoid it, but I think it's still worth it.
=> make the python module also export key functionality from clvm_rs

src/lib.rs, src/merkle_set.rs, wheel/src/api.rs
It treats the leaves as a list to be sorted by a recursive radix sort and implements the hashing along the return path.
This gives a speed-up of about 44 compared to the existing python implementation.
For chia additions, we insert both puzzle hashes and their coins, so 2 merkle values per addition (assuming every addition use a different puzzle hash). With full blocks having ~2000 additions, 4000 merkle values represents a full merkle set.
Tested on an M1
Generating 500 merkle sets of 4000 values:
```
python time: 46.96s
rust time: 1.06s
```
Generating 500 merkle sets with only 100 values:
```
python time: 0.57s
rust time: 0.03s
```
=> function to compute a chia merkle tree root

.github/workflows/benchmark.yml, src/streamable/bytes.rs, tests/test_streamable.py, wheel/py_streamable/src/lib.rs, wheel/src/lib.rs, wheel/src/run_generator.rs, wheel/src/to_json_dict.rs
converting these two type, `PySpend` and `PySpendBundleConditions`, into json isn't critical, but we rely on it for `__str__()` on streamable types, which is used in tests (and one error log).
=> add ToJsonDict trait and generic implementation for Streamable types

src/gen/conditions.rs, src/gen/opcodes.rs
The actual integer value can be debated, I don't have a strong opinion.
I also took the opportunity to assert `cost` in the existing unit tests (in addition to the new one).
The change to enable negative op-codes is a pretty big portion of this patch, and maybe it's not worth it. The patch would be smaller if we pick a positive no-op code.
=> add a condition code that is always true.

.github/workflows/build-arm64-wheels.yml, .github/workflows/build-m1-wheel.yml, .github/workflows/build-test.yml, Cargo.toml, wheel/Cargo.toml, wheel/py_streamable/src/lib.rs, wheel/src/coin.rs, wheel/src/run_generator.rs
This avoids a copy of the entire serialized buffer when calling `parse_rust()`. It especially speeds up wallet sync:
main:
```
INFO     Successfully subscribed and updated 103906 coin ids
INFO     Sync (trusted: True) duration was: 148.95257115364075
```
with this patch:
```
INFO     Successfully subscribed and updated 103906 coin ids
INFO     Sync (trusted: True) duration was: 123.46990084648132
```
The CPU profile of the wallet sync looks like this:
main:
this patch:
=> improve the parse_rust() function to accept a buffer

Cargo.toml, chia_streamable_macro/Cargo.toml, chia_streamable_macro/src/lib.rs, src/bytes.rs, src/streamable.rs, wheel/Cargo.toml, wheel/py_streamable/src/lib.rs, wheel/src/run_generator.rs
This mirrors the python `Streamable` protocol, which has a `get_hash()` function. Although, the one I added here nests by taking the hashing context by mutable reference. The python binding wraps it to give it the same behavior as in python though.
=> add support for get_hash() to the Streamable trait and the derive macro

fuzz/Cargo.toml, fuzz/fuzz_targets/tree-hash.rs, src/gen/get_puzzle_and_solution.rs
harden the `tree_hash()` function by moving away from a recursive implementation.
extend unit test
add fuzzer
=> turn tree_hash() into non-recursive implementation

wheel/src/coin.rs, wheel/src/coin_state.rs, wheel/src/run_generator.rs
This allows them to be used across threads in python
=> make python types sendable

.github/workflows/build-test.yml, src/merkle_set.rs, wheel/src/api.rs, wheel/src/coin.rs, wheel/src/lib.rs, wheel/src/run_generator.rs, wheel/src/run_program.rs
run `cargo fmt` and `cargo clippy` on every crate in the workspace, not just the root
=> Clippy fmt workspace

Cargo.toml, chia_streamable_macro/Cargo.toml, chia_streamable_macro/src/lib.rs, src/streamable.rs, wheel/Cargo.toml
as well as 128 bit integral types in the rust streamable macro.
Plain tuples were already supported (up to a few fields). This adds support for arbitrary types with unnamed members. i.e. when you define a type like this:
```
struct G1Element([u8;48]);
```
This is a step towards being able to have more chia types in rust. The wallet-protocol types are next on my list.
=> support Tuples (unnamed members)

docs/implementation-notes.md
when clvm_rs was split into clvm_rs and chia_rs, this documentation never made it over to the new repo. It belongs in the chia_rs repo as it's specifically talking about parsing the generator output.
This PR also adds another commit on top to describe the new "eligible_for_dedup" feature.
Once this lands, the documentation can be removed from clvm_rs. There's a PR here: https://github.com/Chia-Network/clvm_rs/pull/218
=> move implementation-notes to this repo

.github/workflows/benchmark.yml, .github/workflows/build-test.yml, Cargo.toml, chia-bls/Cargo.toml, chia-bls/README.md, chia-bls/benches/derive_key.rs, chia-bls/benches/sign.rs, chia-bls/benches/verify.rs, chia-bls/fuzz/.gitignore, chia-bls/fuzz/Cargo.toml, chia-bls/fuzz/fuzz_targets/blspy-fidelity.rs, chia-bls/fuzz/fuzz_targets/derive.rs, chia-bls/src/derivable_key.rs, chia-bls/src/derive_keys.rs, chia-bls/src/lib.rs, chia-bls/src/mnemonic.rs, chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs, chia-bls/src/signature.rs
with support for all Chia key operations, from BIP39, hardened and unhardened key derivation, signatures, aggregation and verification.
The overview of the functions added in this crate, see the [README](https://github.com/Chia-Network/chia_rs/blob/28fac7629e71fa9c68600bc2c36c412f0479514d/chia-bls/README.md).
The unit tests include some regression tests against `blspy`, with manual python code snippets.
There are two fuzz targets, one that loads `blspy` and validates results against it ([here](https://github.com/Chia-Network/chia_rs/pull/68/files#diff-28956f0dc0211fe179419220378cbaf20127022210f6bb8a53c8868c45e02582)) and one that checks internal consistency of these functions ([here](https://github.com/Chia-Network/chia_rs/pull/68/files#diff-8e0b9cdf9ef27d60d0026f266b36fd03dd11ac9208211c4f …
=> add new crate chia-bls

.github/workflows/build-crate-and-npm.yml, .github/workflows/build-test.yml, Cargo.toml, clvm-utils/Cargo.toml, clvm-utils/README.md, clvm-utils/fuzz/Cargo.toml, clvm-utils/fuzz/fuzz_targets/tree-hash.rs, clvm-utils/src/lib.rs, clvm-utils/src/tree_hash.rs, fuzz/Cargo.toml, src/gen/get_puzzle_and_solution.rs
this is a pure refactoring. I'm moving the `tree_hash()` function into its own crate `clvm-utils`. This is in preparation of adding more clvm utilities, such as curry/uncurry and computing puzzle-hashes.
=> move tree_hash() into its own crate (clvm-utils)

chia-protocol/src/bytes.rs, chia-protocol/src/from_json_dict.rs, chia-protocol/src/to_json_dict.rs
there were some primitives missing, implementing the traits. This patch also makes a macro to mitigate repetition.
Additionally, another earlier oversight was to not implement the `AsRef` trait for `Bytes` (but just `BytesImpl<n>`). So that's also added.
=> add support for remaining primitive types to json serialization/deserialization

src/merkle_set.rs
This patch adds tests for the edge case where two hashes are only separated by bit 255. The tests are converted from the tests in `chia-blockchain`.
=> improve test coverage of edge case in merkle_tree_set

clvm-utils/fuzz/Cargo.toml, clvm-utils/fuzz/fuzz_targets/tree-hash.rs, clvm-utils/fuzz/fuzz_targets/uncurry.rs, clvm-utils/src/lib.rs, clvm-utils/src/uncurry.rs, fuzz/fuzz_targets/parse-cond-args.rs, fuzz/fuzz_targets/parse-conditions.rs, fuzz/fuzz_targets/puzzle-coin-solution.rs, src/fuzzing_utils.rs
This adds an `uncurry()` function to `clvm-utils`. It's implemented to not allocate a new list for the arguments with the clvm allocator. This enables using it on a potential future read-only allocator.
=> add uncurry() function to clvm-utils

.github/workflows/build-crate-and-npm.yml
When cutting a release, make sure to run all cargo publish, even if some packages can't be published.
This doesn't have all the checks we probably should have, but it at least should make CI green.
=> don't run cargo publish --dry-run on CI

.github/workflows/build-test.yml
lowering the deployment target across the board for all MacOS builds appears to have been a mistake. The M1 builds recently started failing by pip declaring the wheel built against the older MacOS version as not being supported.
Possibly caused by MacOS 10.4 is older than the M1 architecture.
It looks like this ticket may be related: https://github.com/actions/setup-python/issues/469
=> MacOS deployment target on M1

chia-protocol/src/chia_error.rs, chia-protocol/src/chia_protocol.rs, chia-protocol/src/streamable.rs, chia_py_streamable_macro/src/lib.rs, chia_streamable_macro/Cargo.toml, chia_streamable_macro/src/lib.rs, wheel/chia_rs.pyi, wheel/generate_type_stubs.py
This patch adds support for (simple) `enum`s to the `Streamable` macro (in `chia_streamable_macro`). The way it works is it iterates over all enum variants and ensures that:
* they all have an integral value assigned to them
* that the integral value fits in a `u8` variable (because that's what we use for message types)
With this new feature, it's possible to directly use the enums as fields of streamable types, so the `msg_type` and `node_type` are made proper enums.
Rust doesn't allow casting integers to enum variants (but it does support casting enums to ints), therefore, the generated `parse()` function for enums creates a large `match` statement for all integral values, returning the corresponding enum value.
The python binding macro implements py03 conversions for enums to and from …
=> Streamable enums

.github/workflows/build-test.yml, Cargo.toml, chia-protocol/src/bytes.rs, chia-protocol/src/program.rs, chia-tools/Cargo.toml, chia-tools/graph.gnuplot, chia-tools/parse-analyze-chain.py, chia-tools/src/bin/analyze-chain.rs, chia_py_streamable_macro/Cargo.toml, chia_streamable_macro/Cargo.toml
This patch adds a new crate called `chia-tools` along with one program, `analyze-chain`. This is similar to `analyze_chain.py` in the `chia-blockchain` repository.
when analyzing the mainnet blockchain, this tool (along with the log parser and gnuplot scripts) produces plots like these:
=> analyze-chain tool

chia-protocol/src/chia_error.rs
This is a trivial change to implement the [`std::error::Error` trait](https://doc.rust-lang.org/std/error/trait.Error.html) for chia-protocol's `chia_error::Error`. This makes working with `Result`s  that use `chia_error::Error` as error, such as the result obtained from Streamable::parse easier (especially in combination with simple error propagation/handling libraries such as [anyhow](https://github.com/dtolnay/anyhow)).
As `chia_error::Error`s currently don't track any underlying errors, the actual implementation simply stubs out the `source` method to always return `None`.
=> Implement std::error::Error trait for chia-protocol's Error

Cargo.toml, src/gen/conditions.rs
This patch set introduced a dependency on `rstest`, which comes with a few convenient macros to parameterize tests.
It then merges a few test categories into a few parameterized tests. This saves a significant amount of boiler plate code and simplifies the tests. It should also make the tests less error prone since the unique features of the tests are called out in the parameters.
The commits are suitable to be reviewed one at a time.
This patch is in preparation for adding new condition codes, avoiding the test code to blow up in size.
To double check that no test case was dropped by accident, I ran two sanity checks:
```
[main] $ cargo test | wc -l
Finished test [unoptimized + debuginfo] target(s) in 0.25s
Running unittests src/lib.rs (target/debug/deps/chia-d65d6a5ec578387a)
Doc-tests …
```
=> Parameterize tests

src/gen/conditions.rs
Specifically, the tests that adds multiple instances of the same condition and tests how they are aggregated (it's either MAX or SUM right now).
Also the test that has a condition without any arguments, to ensure that error is caught.
This is a follow-up on https://github.com/Chia-Network/chia_rs/pull/129 with a few missed opportunities.
=> parameterize more tests

src/gen/conditions.rs, src/gen/validation_error.rs
If a single spend bundle has an `ASSERT_BEFORE_HEIGHT_ABSOLUTE` that's lower than or equal to another `ASSERT_HEIGHT_ABSOLUTE`, the spend bundle will never be valid.
This patch checks for cases like this. Also for `_SECONDS_ABSOLUTE`.
The `_RELATIVE` checks can only be made within the same Spend, since we don't actually know any absolute timestamps or confirmation heights for the coins.
This is to catch a few obvious invalid cases early.
This still leaves non-obvious cases as successful (and must fail at a later state in the mempool pipeline).
For example, two *different* coins can have `ASSERT_HEIGHT_RELATIVE` and `ASSERT_BEFORE_HEIGHT_RELATIVE` that turn out to conflict, but we'll only know that once we look those coins up from the coin DB and know their confirmation heights.
Another, …
=> add more checks for impossible constraints

src/gen/condition_sanitizers.rs, src/gen/conditions.rs
Specifically, assert_before a negative value is an automatic fail. assert_before a value exceeding the max is an automatic pass.
The two functions used to parse block height and timestamps (seconds) for the original `ASSERT_HEIGHT_*` and `ASSERT_SECONDS_*` has edge-case behavior tailored to those conditions. Those conditions requires the block height or timestamp to exceed the specified limit. If the limit is 0 or negative, the condition is always true. If the limit exceeds the max value however (uint32 and uint64 respectively), the conditions always fail.
Since the `ASSERT_BEFORE_*` conditions have the inverse semantics, the edge case behavior also need to be inverse. This patch introduces `parse_positive_height()` and `parse_positive_seconds()` with the inverse behavior for values …
=> fix edge cases in assert_before parsing

fuzz/Cargo.toml, fuzz/fuzz_targets/sanitize-uint.rs, src/gen/condition_sanitizers.rs, src/gen/conditions.rs, src/gen/mod.rs, src/gen/sanitize_int.rs
this patch separates overflow errors from invalid integer representation errors in the `sanitize_uint()` function. The overflow behaviors are almost always subject to customizations, depending on who's calling it. The invalid integer representations on the other hand, should always just propagate up.
This simplifies the call sites and removes one intermediate layer of functions that currently customize the overflow behavior. Now it's done at each call site.
=> sanitize_uint improvement

.github/workflows/build-test.yml, wheel/src/api.rs, wheel/src/run_generator.rs, wheel/src/run_program.rs
apply `cargo fmt` to `wheel` crate as well. It's been excluded so far because it's excluded from the workspace in `Cargo.toml` (because pyo3 doesn't like to be built with tests)
=> cargo fmt for wheel

chia-tools/Cargo.toml, chia-tools/src/bin/test-block-generators.rs
This runs block generators from a block database in consensus mode and mempool mode, and ensures the outputs are identical.
It's a way to test future mempool tightnening, to ensure no existing block is affected by it.
=> add tool to check equivalence between consensus and mempool

src/gen/conditions.rs, src/gen/opcodes.rs
This patch assign cost to some (currently unknown) condition codes, when the `ENABLE_SOFTFORK_CONDITION` flag is set. Setting this flag is a hard fork, and so is changing the costs of unknown conditions. This flag is intended to be set when the 2.0 hard fork activates.
The rationale for this change is to enable adding new conditions *with cost* as soft forks in the future. It is already possible to soft-fork in new conditions, but they must all have cost 0, since all unknown conditions currently have 0 cost.
Currently, all defined condition codes fit in 1 byte, so `ConditionOpcode` is an alias for `u8`. This patch changes this to be an alias for `u16`. This allows the conditions parser to handle 2-byte conditions.
When the flag `ENABLE_SOFTFORK_CONDITION` is enabled, any 2-byte condition …
=> Unknown conditions with cost

chia-tools/graph.gnuplot, src/allocator.rs, src/gen/flags.rs, wheel/src/api.rs
to restrict the number of atoms and pairs we allow allocating. This overlaps with `LIMIT_HEAP` which also limits the total heap size and is used in mempool-mode.
The intention of this flag is to prepare for soft-forking on just the limit on the number of atoms and pairs.
=> add new flag, LIMIT_OBJECTS

fuzz/Cargo.toml, fuzz/fuzz_targets/process-spend.rs, src/gen/conditions.rs
This opens an opportunity fuzz the internal `process_single_spend()`.
This is a step towards porting the generator ROM to rust, since it allows a way into the condition parsing and validation without first creating the CLVM structure that would have been created by the generator ROM.
=> split up parse_single_spend() into smaller parts

src/gen/conditions.rs, src/gen/flags.rs, src/gen/validation_error.rs
When this flag is enabled, a single spend is not allowed to emit more than 1000 create-announcement, assert-announcement, concurrent spend or coin announcements.
This is a soft-fork and is enabled immediately in mempool-mode.
The objective of this is to make it simpler to avoid DoS vectors, since there's no cost associated with these conditions. The current implementation is careful to not copy messages and data associated with conditions for this reason. With this limit, the implementation would not have to be as careful.
=> Add a flag to restrict the number of announcements

.github/workflows/build-test.yml
The repo to get podman installed on 20.04 is problematic. We have docker available though, so swapping podman -> docker to make the runners easier to manage.
=> Swap podman to docker

chia-protocol/Cargo.toml, chia-protocol/src/bytes.rs, chia-protocol/src/from_json_dict.rs, src/gen/conditions.rs
this make the `Bytes` and `BytesN`-types a bit easier to use, and simplifies some of the test code
=> make Bytes types implement PartialEq

.gitignore, chia-bls/Cargo.toml, chia-protocol/Cargo.toml, chia-tools/Cargo.toml, chia_py_streamable_macro/Cargo.toml, chia_streamable_macro/Cargo.toml, clvm-utils/Cargo.toml, wasm/Cargo.toml, wheel/Cargo.toml
Relax the version pinning on the Rust crates, except for `wheel` and `wasm`.
=> Unpin dependencies

src/gen/mod.rs, src/gen/solution_generator.rs, wheel/chia_rs.pyi, wheel/generate_type_stubs.py, wheel/src/api.rs
This adds a function that creates a (simple) generator given a list of spends. It's a port of `simple_solution_generator` from `chia-blockchain`.
The purpose is to expose the ability to serialize the resulting generator with backrefs. This serialization will be supported when the hard fork activates. Having this functionality now lets us test it in chia-blockchain.
=> solution_generator

.github/workflows/build-test.yml, Cargo.toml, chia-tools/src/bin/test-block-generators.rs, clvm-utils/fuzz/Cargo.toml, clvm-utils/fuzz/fuzz_targets/tree-hash.rs, clvm-utils/fuzz/fuzz_targets/uncurry.rs, fuzz/Cargo.toml, fuzz/fuzz_targets/parse-cond-args.rs, fuzz/fuzz_targets/parse-conditions.rs, fuzz/fuzz_targets/parse-spend.rs, fuzz/fuzz_targets/parse-spends.rs, fuzz/fuzz_targets/process-spend.rs, fuzz/fuzz_targets/puzzle-coin-solution.rs, fuzz/fuzz_targets/self-extractor.rs, fuzz/src/fuzzing_utils.rs, fuzz/src/lib.rs, src/lib.rs
there are two justifications for this:
1. by including the fuzz projects in the main workspace, they share the `Cargo.lock` file with all other build targets, and we ensure that we fuzz the exact same dependencies that we build the production wheel against
2. `cargo fmt --all` and `cargo clippy --workspace` will cover the fuzz targets as well. This lets us simplify the workflow file a bit and also adds new coverage for clippy that we previously did not have
=> include fuzz in workspace

.github/workflows/benchmark.yml
They take a lot of time on a limited runner
=> only run python benchmarks on 3.10 and 3.11

.github/workflows/build-test.yml
With the hope of the fuzzing CI job to have lower runtime
=> adjust times we run the fuzzers in CI

chia-tools/src/bin/test-block-generators.rs, fuzz/fuzz_targets/parse-conditions.rs, src/gen/conditions.rs, src/gen/opcodes.rs, src/gen/run_puzzle.rs, tests/test_streamable.py, wheel/chia_rs.pyi, wheel/generate_type_stubs.py, wheel/src/run_generator.rs
This PR adds support for new `AGG_SIG`-conditions in the same family as `AGG_SIG_ME`.
Since these conditions affect the aggregated signature field on the full block, it is a hard-fork, and is only enabled when the `ENABLE_SOFTFORK_CONDITION`-flag is set.
The new conditions are:
| name | code |
| --- | --- |
| `AGG_SIG_PARENT` | 43 |
| `AGG_SIG_PUZZLE` | 44 |
| `AGG_SIG_AMOUNT` | 45 |
| `AGG_SIG_PUZZLE_AMOUNT` | 46 |
| `AGG_SIG_PARENT_AMOUNT` | 47 |
| `AGG_SIG_PARENT_PUZZLE` | 48 |
They all take the same parameters as `AGG_SIG_ME` and `AGG_SIG_UNSAFE`, i.e. `public-key` and `message`.
The cost are the same as `AGG_SIG_ME` and `AGG_SIG_UNSAFE`, i.e. 1200000.
These act the same as `AGG_SIG_ME`, but instead of including the genesis hash and the coin-id in the signed message, they include a …
=> new agg-sig conditions

chia-protocol/src/bls.rs, chia-protocol/src/chia_protocol.rs, chia-protocol/src/message_struct.rs, chia-protocol/src/program.rs, chia_py_streamable_macro/src/lib.rs, tests/test_streamable.py, wheel/src/run_generator.rs
This lets types use a custom ToJsonDict and FromJsonDict implementation, but still use the PyStreamable macro.
The PyStreamable macro also used to support 1-tuples and treat them as the underlying type. This special case was also removed in this patch, as it was just there to simplify place-holder types.
=> factor out PyJsonDict macro from PyStreamable

wheel/Cargo.toml, wheel/src/api.rs
for backwards compatibility.
The target branch `release-0.2.10` is cut from the `0.2.9` release tag.
=> disable backref encoding for get_puzzle_and_solution_for_coin

Cargo.lock, Cargo.toml, clvm-derive/Cargo.toml, clvm-derive/src/from_clvm.rs, clvm-derive/src/helpers.rs, clvm-derive/src/lib.rs, clvm-derive/src/to_clvm.rs, clvm-traits/Cargo.toml, clvm-traits/src/error.rs, clvm-traits/src/from_clvm.rs, clvm-traits/src/lib.rs, clvm-traits/src/macros.rs, clvm-traits/src/match_byte.rs, clvm-traits/src/to_clvm.rs
This PR adds two crates, one that provides `ToClvm` and `FromClvm` macros and implementations for various common types, and another one that is re-exported in the other that adds derive macros for these traits.
=> Add clvm-traits and clvm-derive crates

wheel/generate_type_stubs.py
to take a list for members instead of a string, that has to include new-lines and indentation
=> improve generate_type_stubs.py

chia-bls/fuzz/fuzz_targets/blspy-fidelity.rs
to help in understanding which pythin is being used by pyo3
=> add helpful comment to blspy-fidelity fuzzer

chia_py_streamable_macro/src/lib.rs
generated by the python streamable macro, to avoid name clashes with rust variants of those functions
=> use py_ prefix for to_bytes() and from_bytes()

Cargo.lock, chia-bls/Cargo.toml, chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs, chia-bls/src/signature.rs
This is in preparation for using the `chia-bls` types in the `chia-protocol` message types, as well as preparing them to be usable from python
=> implement Streamable for bls types

Cargo.lock, chia-bls/Cargo.toml, chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs
as well as allow all-zero secret keys. This is to behave the same as `blspy`.
the same logic in blspy here: https://github.com/Chia-Network/bls-signatures/blob/main/src/elements.cpp#L38-L59
=> check for canonical representation of G1 points (public keys)

chia_py_streamable_macro/src/lib.rs
This may need customization. It still generates `__str__`.
Specifically, the BLS types in `blspy` have different ouput from `__repr__` than `__str__`
=> don't generate `__repr__` in PyStreamable macro

Cargo.lock, chia-bls/Cargo.toml, chia-bls/src/lib.rs, chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs, chia-bls/src/signature.rs
testing this on Apple M1 yields a material speedup:
```
Running benches/derive_key.rs (/Users/arvid/Documents/dev/chia_rs/target/release/deps/derive_key-319a95fb53fa0c95)
secret key, unhardened  time:   [87.483 µs 87.737 µs 88.046 µs]
change: [-71.923% -71.826% -71.742%] (p = 0.00 < 0.05)
Performance has improved.
Found 1 outliers among 100 measurements (1.00%)
1 (1.00%) high mild
secret key, hardened    time:   [440.89 µs 441.48 µs 442.14 µs]
change: [+1.3383% +1.9851% +2.7497%] (p = 0.00 < 0.05)
Performance has regressed.
Found 4 outliers among 100 measurements (4.00%)
1 (1.00%) high mild
3 (3.00%) high severe
public key, unhardened  time:   [92.672 µs 92.827 µs 93.004 µs]
change: [-70.570% -70.500% -70.433%] (p = 0.00 < 0.05)
Performance has improved.
Found 9 outliers among 100 …
```
=> port BLS primitives to using BLST

.github/workflows/benchmark.yml
by not overriding the CC environment variable and don't install clvm_tools from git, just get it from pypi
=> simplify benchmark workflow

chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs, chia-bls/src/signature.rs
Simplifies a few tests and derives the `Default` trait instead of implementing it manually.
The last 3 commits move tests into their own `mod` to make them a bit less verbose. These are best reviewed ignoring white space changes, since their indentation level changed.
=> blspy fixups

chia-protocol/src/bytes.rs, chia-protocol/src/program.rs, chia-traits/src/chia_error.rs, tests/test_streamable.py
when parsing a string from a Json Dict containing a CLVM program, reject strings that have garbage at the end, or otherwise has invalid CLVM serialization.
=> validate program when parsing it from JsonDict

src/gen/conditions.rs, wheel/Cargo.toml
This fixes a bug when parsing the new `AGG_SIG_*` conditions in mempool mode.
The affected conditions are:
1. `AGG_SIG_PARENT`
2. `AGG_SIG_PUZZLE`
3. `AGG_SIG_AMOUNT`
4. `AGG_SIG_PUZZLE_AMOUNT`
5. `AGG_SIG_PARENT_PUZZLE`
6. `AGG_SIG_PARENT_AMOUNT`
In mempool mode, we require the exact correct number of arguments to be passed to conditions. Whereas in consensus mode we're more forgiving, to allow for soft-forks. The test for an NIL-terminator was incorrect and always looked at the last *cons* cell, not the last item in the list. This made this test fail unconditionally.
The bulk of this change is to extend the tests to cover this case.
The original feature landed here: https://github.com/Chia-Network/chia_rs/pull/213
This PR is targeting a new branch called `release-0.2.11` which was cut …
=> fix bug in enforcing nil-termination of new AGG_SIG_* conditions

.github/workflows/build-test.yml, Cargo.toml, src/gen/mod.rs, src/gen/test_generators.rs
the CI fuzz job goes from: 42m -> 13m
=> various changes to speed-up CI runs

chia-bls/src/lib.rs, chia-bls/src/public_key.rs, chia-bls/src/signature.rs
add negate, scalar_multiply, hash_to_g1, from_integer to point types as well as hash_to_g2.
These operations are sufficient to make `clvm_rs` use this crate instead of `bls12_381`
=> more BLS operations

.github/workflows/build-crate-and-npm.yml, chia-bls/Cargo.toml, chia-protocol/Cargo.toml, chia-traits/Cargo.toml
this patch updates the github workflow to publish more of our crates when we tag a release. The order matters, because some crates depend on others.
In order to be publishable, we need versions for all dependencies, including the ones we build from the local repo. That's the main fix to `chia-bls`, to enable it to be published.
=> update chia-bls crate to prepare for publishing to crates.io

Cargo.lock, Cargo.toml, chia-bls/fuzz/Cargo.toml, chia-bls/fuzz/fuzz_targets/blspy-fidelity.rs, chia-bls/fuzz/fuzz_targets/derive.rs, chia-bls/src/public_key.rs, chia-bls/src/signature.rs, chia-protocol/fuzz/Cargo.toml, chia-protocol/fuzz/fuzz_targets/parse-foliage.rs, chia-protocol/fuzz/fuzz_targets/parse-full-block.rs, chia-protocol/fuzz/fuzz_targets/parse-header-block.rs, chia-protocol/fuzz/fuzz_targets/parse-program.rs, chia-protocol/fuzz/fuzz_targets/parse-tx-info.rs, clvm-traits/src/to_clvm.rs
this makes them covered by `cargo clippy --workspace`.
As a result, some new `clippy` issues are exposed and fixed
=> include fuzzers in workspace

bump-version.py, chia-tools/Cargo.toml, wheel/Cargo.toml
This tool checks each crate for changes since the last release tag (as specified on the command line). Any crate that has had changes has its version updated to the latest version (also specified on the command line).
All internal dependencies of crates are update to match this version.
This is meant to simplify and make releases less error prone.
=> tool to bump crate versions

Cargo.lock, chia-bls/Cargo.toml, chia-bls/src/public_key.rs, chia-bls/src/secret_key.rs, chia-bls/src/signature.rs, chia-protocol/Cargo.toml, chia-protocol/fuzz/Cargo.toml, chia-protocol/fuzz/fuzz_targets/parse-foliage.rs, chia-protocol/fuzz/fuzz_targets/parse-full-block.rs, chia-protocol/fuzz/fuzz_targets/parse-header-block.rs, chia-protocol/fuzz/fuzz_targets/parse-program.rs, chia-protocol/fuzz/fuzz_targets/parse-tx-info.rs, chia-protocol/fuzz/fuzz_targets/streamable.rs, chia-protocol/src/bytes.rs, chia-protocol/src/chia_protocol.rs, chia-protocol/src/message_struct.rs, chia-protocol/src/program.rs, chia-traits/src/streamable.rs
This PR:
* Adds a fuzzer for `update_digest()` as well as round-trip serializing.
* Makes message types implement the `Arbitrary` trait when building in fuzzing mode.
* Adds utility functions, `to_bytes()`, `from_bytes()` and `hash()` on the Streamable trait
=> add fuzzer for streamable

chia-protocol/src/weight_proof.rs, wheel/chia_rs.pyi, wheel/generate_type_stubs.py
These members are defined here, in `chia-blockchain`:
https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/weight_proof.py#L59-L67
=> add member functions to `SubSlotData`

chia-tools/src/bin/analyze-chain.rs, chia-tools/src/bin/test-block-generators.rs, fuzz/fuzz_targets/fast-forward.rs, fuzz/fuzz_targets/parse-conditions.rs, fuzz/fuzz_targets/parse-spends.rs, fuzz/fuzz_targets/process-spend.rs, fuzz/fuzz_targets/run-generator.rs, fuzz/fuzz_targets/run-puzzle.rs, src/fast_forward.rs, src/gen/conditions.rs, src/gen/flags.rs, src/gen/mod.rs, src/gen/policy.rs, src/gen/run_block_generator.rs, src/gen/run_puzzle.rs, src/gen/spend_visitor.rs, src/gen/test_generators.rs, wheel/src/api.rs, wheel/src/run_generator.rs
when parsing and validating conditions. This indicates whether some of the requirements are met to be able to fast-forward a singleton spend.
This patch also introduces a customization class (`ConditionPolicy`) to hook into the parsing of conditions. the `ELIGIBLE_FOR_DEDUP` is moved out into the mempool-mode policy, and the new `ELIGIBLE_FOR_FF` is added to that same policy class.
The other policy is `NonePolicy`, which is used in consensus mode, which doesn't do any extra analysis of spends.
Given the simplicity of the two spend analyses (implemented in `MempoolPolicy`) it's not obvious to me that this abstraction and customization point carries its own weight. I think it's a net increase in complexity.
All the "business logic" for this patch is concentrated here: …
=> introduce ELIGIBLE_FOR_FF flag on Spends via policy class

chia-bls/Cargo.toml
`blspy` builds it in portable mode, and not being portable is likely what's causing CI in chia-blockchain to fail with `SIGILL`.
https://github.com/Chia-Network/bls-signatures/blob/main/src/CMakeLists.txt#L47
=> bump blst dependency, and build it in portable mode

chia_py_streamable_macro/src/lib.rs, tests/test_streamable.py
otherwise it's not possible to directly pass in a slice of a `bytes` object. i.e. `.from_bytes(b[1:])`. It would have to be copied into a new `bytes` object first, i.e. `.from_bytes(bytes(b[1:]))`
=> make `from_bytes()` accept python's buffer API

chia-protocol/fuzz/fuzz_targets/streamable.rs, chia-traits/src/streamable.rs, chia_py_streamable_macro/src/lib.rs, tests/test_streamable.py
It requires the input be an exact match, no extra bytes at the end. This is to make it behave the same as `from_bytes()` in `chia-blockchain`
=> `from_bytes()` fix

.github/workflows/build-crate-and-npm.yml
the root crate (chia_rs) depends on chia-wallet, so it needs to be published before we can publish chia_rs.
It's meant to address this error: https://github.com/Chia-Network/chia_rs/actions/runs/6695380930/job/18190836509#step:21:14
=> publish `chia-wallet` crate

Cargo.lock, Cargo.toml, chia-bls/Cargo.toml, chia-protocol/Cargo.toml, chia-protocol/fuzz/Cargo.toml, chia-traits/Cargo.toml, wheel/Cargo.toml
(except internal dependencies).
Bump `hkdf` dependency to enable bumping `sha2` version. This deduplicates the depency, to only depend on a single version of `sha2`.
The reason to keep internal dependencies exact is to let us assume all versions are incompatible (for now), until development settles down and we may actually be able to maintain stable APIs.
=> relax versions of dependencies

chia-bls/src/secret_key.rs, chia-protocol/src/bytes.rs, chia-tools/src/bin/fast-forward-spend.rs, chia-traits/src/streamable.rs
=> optimize Vec<T>::parse(), for Streamable

.github/workflows/benchmark.yml
We no longer support python 3.7
=> disable build for python 3.7

wheel/chia_rs.pyi, wheel/generate_type_stubs.py
`first_in_sub_slots` -> `first_in_sub_slot`.
The correct names are found [here](https://github.com/Chia-Network/chia_rs/blob/main/chia-protocol/src/header_block.rs#L132) and [here](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/header_block.py#L64).
=> fix typo in type stubs for HeaderBlock

.github/workflows/audit-check.yml, Cargo.lock, chia-ssl/Cargo.toml
This addresses a `cargo audit` issue:
```
Fetching advisory database from `https://github.com/RustSec/advisory-db.git`
Loaded 579 security advisories (from /Users/arvid/.cargo/advisory-db)
Updating crates.io index
Scanning Cargo.lock for vulnerabilities (298 crate dependencies)
Crate:     rsa
Version:   0.9.3
Title:     Marvin Attack: potential key recovery through timing sidechannels
Date:      2023-11-22
ID:        RUSTSEC-2023-0071
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0071
Solution:  No fixed upgrade is available!
Dependency tree:
rsa 0.9.3
└── chia-ssl 0.2.13
```
our current use of the `rsa` crate is to generate certificates to connect to chia nodes.
=> suppress RSA security alert

Cargo.lock, Cargo.toml, chia-bls/Cargo.toml, chia-protocol/Cargo.toml, chia-tools/Cargo.toml, chia-wallet/Cargo.toml, chia-wallet/fuzz/Cargo.toml, clvm-traits/Cargo.toml, clvm-traits/docs/derive_macros.md, clvm-traits/src/clvm_decoder.rs, clvm-traits/src/clvm_encoder.rs, clvm-traits/src/from_clvm.rs, clvm-traits/src/lib.rs, clvm-traits/src/to_clvm.rs, clvm-utils/Cargo.toml, clvm-utils/fuzz/Cargo.toml, fuzz/Cargo.toml, wheel/Cargo.toml
remove the `ToNodePtr` and `FromNodePtr` traits as well as `FromClvm` and `ToClvm` for `Allocator` and `NodePtr` (those will be moved into `clvmr`).
This is one step in untangling the dependency cycle caused by making `clvmr` use `chia-bls`.
In order to keep everything building, all other crates that depend on `clvm-traits` now use the crates.io version (i.e. stay on the current version).
once this lands, `clvm_rs` can be updated to implement the `clvm-traits`. Then this repository can be restored to depend on the new `clvm_rs` and `clvm-traits`
=> drop clvm-trait's dependency on clvmr

Cargo.lock, chia-tools/Cargo.toml, chia-tools/src/bin/analyze-chain.rs, chia-tools/src/bin/test-block-generators.rs, chia-tools/src/visit_spends.rs
`rusqlite` appears to be much more established and popular in the rust ecosystem. But more importantly, it has much more complete support for sqlite features, which are required for the event-log analysis tool I'm building.
While working in these files, I took the opportunity to transition `test_block_generators.rs` to use the (somewhat new) higher level abstraction to iterate over the transaction blocks in a blockchain database. This reduces a fair amount of duplicated code.
=> switch rust wrapper for sqlite in chia-tools

Cargo.lock, Cargo.toml, bump-version.py, chia-bls/Cargo.toml, chia-client/Cargo.toml, chia-protocol/Cargo.toml, chia-tools/Cargo.toml, chia-traits/Cargo.toml, chia-wallet/Cargo.toml, chia-wallet/fuzz/Cargo.toml, chia_py_streamable_macro/Cargo.toml, chia_streamable_macro/Cargo.toml, clvm-traits/Cargo.toml, clvm-utils/Cargo.toml, clvm-utils/fuzz/Cargo.toml, fuzz/Cargo.toml, wheel/Cargo.toml
This prepares for publishing the new `clvm-traits` that does not include `ToNodePtr`, `FromNodePtr` traits, as well as implementations for `Allocator` and `NodePtr`.
Note that since `clvmr` isn't updated yet, all other crates still depend on the 0.2.14 version of `clvm-traits`. Once this is published, we can update `clvmr` and restore the crates to depend on the local version in this repo.
=> Bump version to 0.3.0

chia-wallet/Cargo.toml
Fixes an error in the release because of the version of one crate bumping before publishing another.
=> Pin versions

Cargo.toml, chia-bls/Cargo.toml, chia-protocol/Cargo.toml, chia-traits/Cargo.toml, chia-wallet/Cargo.toml, clvm-traits/Cargo.toml, clvm-utils/Cargo.toml
As long as we follow semver compatibility, this should help prevent version conflicts when installing our library crates.
=> Unpin dependencies for library crates

fuzz/fuzz_targets/fast-forward.rs, src/fast_forward.rs, src/gen/conditions.rs
Update the fast-forward feature to allow the coin amount to change when "rebasing" a spend onto a later version of the same singleton.
=> relax coin amount in fast-forward logic

.github/workflows/benchmark.yml, .github/workflows/build-test.yml, chia-protocol/src/program.rs, tests/test_program_fidelity.py
for purposes of converting it from python structures.
This patch updates the behavior of converting a python structure into a `Program`. This fixes fidelity with the python implementation for how `SerializedProgram` is treated. In python it hits [this](https://github.com/Chia-Network/clvm/blob/main/clvm/SExp.py#L52-L53) case, and converts to `bytes`.
This is now correctly reflected in the `clvm_convert()` function. The test was expanded to cover this case.
This requires a recent version of the `clvm` wheel, (0.9.8).
=> Program as a bytes buffer

chia-protocol/src/program.rs, tests/test_program_fidelity.py
to match `SerializedProgram._run()`.
This is a bit messy, see comment in `Program.rs`
=> fix argument conversion for `Program::_run()`

.github/workflows/benchmark.yml, .github/workflows/build-crate-and-npm.yml, .github/workflows/build-test.yml
[https://github.com/actions-rs/toolchain](actions-rs/toolchain) is archived and unmaintained, so we should use [https://github.com/dtolnay/rust-toolchain](dtolnay/rust-toolchain) instead.
=> Switch to dtolnay/rust-toolchain

wheel/chia_rs.pyi, wheel/generate_type_stubs.py
`HeaderBlock` is missing type annotation for `prev_hash`.
It's defined here: https://github.com/Chia-Network/chia_rs/blob/main/chia-protocol/src/header_block.rs#L90
and here in the python counterpart: https://github.com/Chia-Network/chia-blockchain/blob/main/chia/types/header_block.py#L36
=> add missing type annotation of HeaderBlock

.github/workflows/audit-check.yml, .github/workflows/benchmark.yml, Cargo.toml, chia-bls/src/secret_key.rs, chia-protocol/src/bytes.rs, chia-tools/Cargo.toml, chia-tools/src/bin/fast-forward-spend.rs, wheel/Cargo.toml
this was automated by running:
```
python bump-version.py 0.2.15 0.2.13
```
Also
- remove python 3.7 from the benchmark test matrix
- update the cargo audit check workflow to match main
- minor fixes needed for clippy due to changes in rust 1.75 (current stable) that were not in the version of rust used at the time of `0.2.13`
=> bump version to 0.2.15 using bump-version.py

.github/workflows/build-test.yml, Cargo.lock, Cargo.toml, chia-bls/Cargo.toml, wheel/Cargo.toml
Use clang on windows and a target git reference for BLST to force BLST to compile SHA256 into portable mode.
This addresses the problem with AMD K10 architecture on Windows.
=> Address issues with windows AMD K10 architecture - Build with clang for portable SHA256

chia-protocol/fuzz/fuzz_targets/streamable.rs, chia-protocol/src/block_record.rs, chia-protocol/src/lib.rs, tests/test_block_record_fidelity.py, wheel/chia_rs.pyi, wheel/generate_type_stubs.py, wheel/src/api.rs
This PR is best reviewed one commit at a time.
This adds the `BlockRecord` type, defined in python [here](https://github.com/Chia-Network/chia-blockchain/blob/main/chia/consensus/block_record.py#L46).
The main challenge in this type is implementing `sp_sub_slot_total_iters()`, `ip_sub_slot_total_iters()`, `sp_iters()`, `ip_iters()`, `sp_total_iters()`. The underlying functions used by these are implemented in python.
This patch calls back into python to run these functions. It's not elegant or efficient, but it's a stop-gap until we have ported these functions to rust.
In order to ensure this works, a fuzzer constructs an arbitrary `BlockRecord` object and calls all these functions on both the rust and python version, ensuring the results are identical, including failures.
=> add BlockRecord

Cargo.lock, chia-client/Cargo.toml, chia-client/src/error.rs, chia-client/src/peer.rs
This adds various helper methods to `Peer` to simplify the process of sending requests, provide better type safety, and handle rejections as part of the error variant of the response.
Message ids beyond `u16::MAX` would also previously panic in debug mode, but now a thread-safe `AtomicU16` is used instead of `Mutex<u16>`, which also means it will wrap on overflow instead of panicking.
=> Add methods to peer and make message ids atomic

.github/workflows/benchmark.yml, .github/workflows/build-test.yml
Add python 3.12 to matrix
Remove old exclusion of python 3.7 since it's not used anymore
Note, test matrix does not specify 3.12 since it requires the wheel to get all published first
=> Add python 3.12

Cargo.toml, benches/run-generator.rs, benches/tree-hash.rs
This PR is best reviewed one commit at a time. The second commit introduces a change in indentation, so ignoring whitespace will make it easier to see what's happening.
There are to changes:
* a new `tree-hash` benchmarks is added
* the existing `run-generator` benchmark is amended to run all blocks as both uncompressed and compressed (i.e. clvm backrefs)
=> Tree hash benchmark

chia-protocol/src/bytes.rs, chia-protocol/src/classgroup.rs, chia-protocol/src/program.rs, chia-protocol/src/spend_bundle.rs, chia-tools/src/bin/fast-forward-spend.rs, chia-tools/src/bin/gen-corpus.rs, chia-tools/src/visit_spends.rs, fuzz/fuzz_targets/fast-forward.rs, src/fast_forward.rs, src/gen/coin_id.rs, src/gen/conditions.rs, src/gen/get_puzzle_and_solution.rs, src/gen/run_puzzle.rs, src/gen/test_generators.rs, wheel/src/run_generator.rs
This PR adds missing conversions for `Bytes`, `BytesImpl`, and `Program`, and removes `PartialEq` implementations for other types to reduce complexity.
It also changes `From` to `TryFrom` in some cases where the conversion is fallible:
> **Note: This trait must not fail.** The `From` trait is intended for perfect conversions. If the conversion can fail or is not perfect, use `TryFrom`.
https://doc.rust-lang.org/std/convert/trait.From.html
=> Update trait impls and conversions for byte types

chia-protocol/src/block_record.rs, chia-protocol/src/bytes.rs, chia-protocol/src/chia_protocol.rs, chia-protocol/src/fullblock.rs, chia-protocol/src/header_block.rs, chia-protocol/src/message_struct.rs, chia-protocol/src/unfinished_block.rs, chia-traits/src/int.rs, chia-traits/src/lib.rs, chia_py_streamable_macro/src/lib.rs, tests/test_block_record_fidelity.py, tests/test_coin.py, tests/test_replace.py, tests/test_streamable.py, wheel/chia_rs.pyi, wheel/generate_type_stubs.py
This is an alternative approach to https://github.com/Chia-Network/chia_rs/pull/378
It uses a trait to recursively convert the rust types into python, which is better in my mind.
It's a lot simpler and robust to use a trait for this. The downside is that rust doesn't support trait specializations or negative trait bounds, so it's not possible to defer all non-covered types to a default implementation.
There does not seem to be a slow-down.
```
232.64s call     tests/test_block_record_fidelity.py::test_block_record
8.56s call     tests/test_program_fidelity.py::test_uncurry
7.17s call     tests/test_blspy_fidelity.py::test_bls
1.16s call     tests/test_program_fidelity.py::test_round_trip
0.91s call     tests/test_program_fidelity.py::test_run_program
0.42s call …
```
=> expose integers as our fixed-width integer types from chia-blockchain

chia-tools/Cargo.toml, chia-tools/src/bin/optimize-db.rs
testing this on my blockchain database:
```
peak block hash: 7a7546d1cac0270fe25bdd7bbaba0d4ed48626eb3859d39a88eb7da0f2d32aff
peak height: 4878515
dropping orphaned blocks...
removed 6574 orphaned blocks
2799635 fully compact blocks (57.39%)
analyze block table
analyze coins table
analyze hints table
vacuum into mainnet-test.db
all done!
```
| before | after | after/before |
| --- | --- | --- |
| 163018407936 | 152597893120 | 93.6 % |
=> add tool to optimize a blockchain database

chia-wallet/src/puzzles/cat.rs, chia-wallet/src/puzzles/standard.rs
Adds a way to calculate the puzzle hash of a CAT without generating the full puzzle.
=> Add CAT puzzle hash calculation

.github/workflows/build-riscv64.yml
The release workflow wasn't setup correctly, so the release publishing step to publish the riscv wheels to `pypi.chia.net` wasn't working correctly
Hopefully this fixes that problem
Also fixed up copy paste error
=> Fix release workflow for riscv

chia-tools/src/bin/analyze-chain.rs
this patch is best viewed with whitespace changes ignored, since there's a large section with its indentation changed.
=> simplify analyze-chain.rs by using the let-else construct

Cargo.toml, wheel/Cargo.toml
This is no longer necessary since we removed the dependency from `clvmr`.
=> Remove clvm-traits patch.crates-io entry

Cargo.lock, chia-protocol/src/program.rs
same treatment as the fixed-width integers
=> optimize conversion to python Program class

Cargo.lock, benches/tree-hash.rs, chia-protocol/src/program.rs, clvm-utils/src/tree_hash.rs, wheel/Cargo.toml, wheel/src/api.rs
I don't think anything depends on this (yet), but not supporting it is inconsistent between `SerializedProgram` and `Program` (in `chia-blockchain`) and a risk.
There are optimizations to improve performance of computing the tree hash for clvm structures with backrefs that I intend to explore. But the first step is to support it in the first place.
=> make tree_hash() support CLVM with backrefs

chia-protocol/src/bytes.rs, tests/test_block_record_fidelity.py
Now that we have the infrastructure to have these custom conversions, we might as well do it for `bytes32` as well.
This addresses a lot of risks when using these types in chia-blockchain, as we don't have test coverage for all places we print `bytes32` objects for instance.
=> expose bytes32 as the right type, from chia-blockchain

chia-protocol/src/program.rs, tests/test_program.py, wheel/src/adapt_response.rs, wheel/src/api.rs, wheel/src/run_program.rs
improve conversion from `EvalErr` to `ValueError` in python. in `Program._run()`, we did not convert the error consistently with other places (and lost information). This fixes that and adds a test.
Thanks for the report, @trepca
=> add test for (x) error message

Cargo.lock, Cargo.toml, chia-protocol/Cargo.toml, chia-protocol/fuzz/Cargo.toml, chia-protocol/fuzz/fuzz_targets/spend-bundle.rs, chia-protocol/src/bytes.rs, chia-protocol/src/lazy_node.rs, chia-protocol/src/spend_bundle.rs, chia-tools/Cargo.toml, chia-tools/src/visit_spends.rs, chia-wallet/Cargo.toml, chia-wallet/fuzz/Cargo.toml, clvm-traits/Cargo.toml, clvm-traits/src/clvm_decoder.rs, clvm-traits/src/from_clvm.rs, clvm-traits/src/match_byte.rs, clvm-utils/Cargo.toml, clvm-utils/fuzz/Cargo.toml, clvm-utils/src/tree_hash.rs, fuzz/Cargo.toml, src/gen/condition_sanitizers.rs, src/gen/conditions.rs, src/gen/get_puzzle_and_solution.rs, src/gen/opcodes.rs, src/gen/sanitize_int.rs, src/gen/test_generators.rs, src/gen/validation_error.rs, wheel/Cargo.toml, wheel/src/run_generator.rs
the new `clvmr` crate has a slightly new API for `Allocator::atom()`. The second commit in this PR adapts `chia_rs` to this API.
=> Bump clvm 0.6.0

Cargo.lock, clvm-utils/Cargo.toml, clvm-utils/fuzz/fuzz_targets/tree-hash.rs, clvm-utils/src/tree_hash.rs, src/gen/run_block_generator.rs
This PR introduces an optimization of puzzle hash computations. It will take effect after the hard fork, when blocks are generated in compressed CLVM form (i.e. with back-references).
speed-up of tree hashing a block generators. These are blocks from mainnet, but re-serialized in compressed form.
| block | speed-up (AMD)| speed-up (RPi5) | speed-up (M1) |
| --- | --- | --- | --- |
| 1ee588dc  |   5.08  | 5.95 | 6.19 |
| 225758  |   1.00   | 1.1 | 1.15 |
| 4671894 |   1.13  | 1.29 | 1.35 |
| 6fe59b24 | 4.15 |  5.09 | 4.98 |
| 834752 |  3.64 | 4.27 | 4.45 |
| b45268ac  | 5.00  | 6.02 |6.23 |
| c2a8df0d  | 5.85 | 6.99 | 7.52 |
speed-up of running block generators (with the rust implementation of the generator ROM, i.e. post hard-fork). Since this also runs CLVM and partially validates …
=> `tree_hash_cached()`

.github/workflows/build-crate-and-npm.yml, .github/workflows/build-test.yml
This change is to prevent nightly clippy lints from breaking CI like https://github.com/rust-lang/rust/issues/121621.
=> Use stable for CI tests, clippy, build

.github/workflows/build-test.yml
introduced here https://github.com/Chia-Network/chia_rs/actions/runs/8054706840
```
[Error: .github#L1](https://github.com/Chia-Network/chia_rs/commit/dde6811b64a858dfb01e6a9d6915b254a69da6b0#annotation_18556478120)
the `uses' attribute must be a path, a Docker image, or owner/repo@ref
```
=> fix typo in workflow file

crates/chia-consensus/fuzz/fuzz_targets/parse-cond-args.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-conditions.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-spend.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-spends.rs, crates/chia-consensus/fuzz/src/fuzzing_utils.rs
for `cargo fuzz run parse-conditions`
main:
```
#101362 REDUCE cov: 555 ft: 2458 corp: 167/8395b lim: 497 exec/s: 2472 rss: 120Mb L: 18/288
```
new:
```
#107417 REDUCE cov: 1525 ft: 3197 corp: 284/3923b lim: 857 exec/s: 8951 rss: 108Mb L: 17/107
```
=> improve fuzzer coverage

crates/chia-consensus/src/gen/conditions.rs
the `STRICT_ARGS_COUNT` flag is used in mempool mode to restrict the number of arguments passed to conditions to just the one we support. i.e. no unknown arguments.
There are some complicated rules around `AGG_SIG_ME` and `AGG_SIG_UNSAFE`, since they never supported any additional parameters, not even in consensus mode. In the hard fork, this restriction will be lifted, and these conditions will behave like all other conditions. However, we still want to restrict the number of parameters used in mempool mode (just like other conditions)
=> improve STRICT_ARGS_COUNT flag

.pre-commit-config.yaml
This speeds up the precommit hook by about 50%, cutting it from 3:02 to 1:37 on my machine.
=> Change precommit bench build to dev

crates/chia-consensus/fuzz/Cargo.toml, crates/chia-consensus/fuzz/fuzz_targets/parse-cond-args.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-conditions.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-spend-id.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-spends.rs, crates/chia-consensus/src/gen/condition_sanitizers.rs, crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/flags.rs, crates/chia-consensus/src/gen/messages.rs, crates/chia-consensus/src/gen/mod.rs, crates/chia-consensus/src/gen/opcodes.rs, crates/chia-consensus/src/gen/validation_error.rs, crates/chia-tools/src/bin/run-spend.rs, wheel/src/api.rs
This PR implements the message condition codes as described by [CHIP-25](https://github.com/Chia-Network/chips/pull/98).
Support for these new conditions is *disabled* by default, and only enabled by passing in the `ENABLE_MESSAGE_CONDITIONS` flag. (the enable/disable logic is implemented in `crates/chia-consensus/src/gen/opcodes.rs`).
There are 3 new error codes introduced by this PR. These will need to be added to `chia-blockchain` as well.
```
ErrorCode::InvalidMessageMode => 145,
ErrorCode::InvalidCoinId => 146,
ErrorCode::MessageNotSentOrReceived => 147,
```
Since there's no CLVM cost associated with these new conditions, we need to be careful to mitigate abuse in the form of DoS attacks. When a message is sent or received, we record as little information as possible up front, to …
=> Message conditions

Cargo.lock, Cargo.toml, bump-version.py, crates/chia-bls/Cargo.toml, crates/chia-client/Cargo.toml, crates/chia-consensus/Cargo.toml, crates/chia-consensus/fuzz/Cargo.toml, crates/chia-protocol/Cargo.toml, crates/chia-ssl/Cargo.toml, crates/chia-tools/Cargo.toml, crates/chia-traits/Cargo.toml, crates/chia-wallet/Cargo.toml, crates/chia-wallet/fuzz/Cargo.toml, crates/chia_py_streamable_macro/Cargo.toml, crates/chia_streamable_macro/Cargo.toml, crates/clvm-derive/Cargo.toml, crates/clvm-traits/Cargo.toml, crates/clvm-utils/Cargo.toml, crates/clvm-utils/fuzz/Cargo.toml, wheel/Cargo.toml
first commit: fixes an issue in `bump-version.py` from when crates were moved into a subdirectory.
second commit: bump version to 0.6.0
=> Bump version 0.6.0

crates/clvm-utils/src/tree_hash.rs
Fixes a bug in the tests on Windows.
=> Swap to .lines().next() instead of .split_once('\n')

crates/chia-consensus/src/merkle_set.rs
This enables using the same test cases in the forthcoming `MerkleSet` type.
=> factor out the merkle tree test cases

crates/chia-consensus/src/merkle_set.rs, crates/chia-consensus/src/merkle_tree.rs
* make the `MerkleSet` tests use the same test cases as `compute_merkle_set_root()`
* fix for-loops in `test_random_bytes()` and `test_bad_proofs()`
=> improvements to Merkle tests

crates/chia-protocol/src/bytes.rs, crates/chia-traits/src/int.rs
instead of types from `chia.types.blockchain_format`
=> in the python binding, use the local types

crates/chia-consensus/src/merkle_tree.rs
Creates a stack of bits vecs and pops them to match the flow of the while loop of deserialisation.
=> Add leaf audit to proof deserialization

crates/chia-consensus/fuzz/fuzz_targets/merkle-set.rs, crates/chia-consensus/src/merkle_tree.rs
"Merkle" is implied and this matches the existing python name.
=> rename get_merkle_root() -> get_root()

tests/merkle_set.py
This copies the current version of `chia/utils/merkle_set.py` from the main branch in `chia-blockchain`. It appears this repo uses different black configuration, so it had to be re-formatted.
Copying this class into the repo is a way to avoid adding more dependencies on the `chia-blockchain` project (which is a circular dependency).
=> Merkle set from blockchain

crates/chia-consensus/benches/merkle-set.rs, crates/chia-consensus/fuzz/fuzz_targets/merkle-set.rs, crates/chia-consensus/src/merkle_tree.rs, tests/test_merkle_set.py
and add comments describing how it works
=> restore support for proofs of exclusion in MerkleSet

crates/chia-consensus/src/gen/solution_generator.rs, crates/chia-protocol/src/coin.rs, crates/chia-protocol/src/coin_state.rs, crates/chia-protocol/src/spend_bundle.rs
Every field of `Coin` and `CoinState` implements `Copy`, so it seems like a good idea for them to as well.
It's also recommended to do so whenever possible without potential public API breakage in the future:
https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy
=> Implement Copy for Coin and CoinState

crates/chia-consensus/src/error.rs, crates/chia-consensus/src/fast_forward.rs, crates/chia-tools/src/bin/run-spend.rs, crates/chia-wallet/fuzz/fuzz_targets/roundtrip.rs, crates/chia-wallet/src/proof.rs, crates/chia-wallet/src/puzzles/singleton.rs
There were duplicated types between `chia-wallet` and `chia-consensus`, so this makes `chia-consensus` use `chia-wallet`'s types instead and simplifies the API for lineage proofs.
=> Simplify lineage proof and remove chia-consensus singleton types

crates/chia-bls/benches/verify.rs, crates/chia-bls/src/gtelement.rs, crates/chia-bls/src/lib.rs, crates/chia-bls/src/signature.rs
to prepare for the BLS cache.
Validating an aggregate signature in BLS can be broken down into the following steps:
1. for each (public key, message)-pair
1.1 augment the message by pre-pending the public key. The public key is also known as G1.
1.2 map the augmented message to G2 (`hash_to_g2()`)
1.3 pair the G1 and G2 points to get a GT point
2. multiply all GT points together
3. pair the generator (a G1 point) with the signature (a G2 point)
4. if the aggregate GT point equals the signature pair, the signature is valid.
The pairing operation is quite expensive. As you can see from the benchmark, validating a signature against 1000 GT points is 2 orders of magnitude faster than validating 1000 (key, message)-pairs. The BLS cache caches the GT points to avoid having to compute the …
=> expose aggregate_verify_gt() in chia-bls

crates/chia-bls/src/public_key.rs, crates/chia-bls/src/signature.rs, crates/chia-puzzles/src/proof.rs, crates/chia-puzzles/src/puzzles/cat.rs, crates/chia-puzzles/src/puzzles/did.rs, crates/chia-puzzles/src/puzzles/nft.rs, crates/chia-puzzles/src/puzzles/singleton.rs, crates/chia-puzzles/src/puzzles/standard.rs
Implement `Copy` whenever possible for `PublicKey` and puzzles types and `Arbitrary` for puzzle types.
=> Derive Copy and Arbitrary for types when possible

crates/chia-consensus/src/fast_forward.rs, crates/chia-consensus/src/gen/get_puzzle_and_solution.rs, crates/chia-consensus/src/gen/run_block_generator.rs, crates/chia-protocol/src/bytes.rs, crates/chia-puzzles/src/derive_synthetic.rs, crates/chia-puzzles/src/puzzles/cat.rs, crates/chia-puzzles/src/puzzles/did.rs, crates/chia-puzzles/src/puzzles/nft.rs, crates/chia-puzzles/src/puzzles/offer.rs, crates/chia-puzzles/src/puzzles/singleton.rs, crates/chia-puzzles/src/puzzles/standard.rs, crates/chia-tools/src/bin/gen-corpus.rs, crates/clvm-utils/Cargo.toml, crates/clvm-utils/fuzz/fuzz_targets/tree-hash.rs, crates/clvm-utils/src/curry_tree_hash.rs, crates/clvm-utils/src/hash_encoder.rs, crates/clvm-utils/src/lib.rs, crates/clvm-utils/src/tree_hash.rs
Instead of having to special case untyped currying code with `curry_tree_hash` for each puzzle type, you can use `CurriedProgram` directly now. Here is an example:
```rs
let puzzle_hash = CurriedProgram {
program: CAT_PUZZLE_HASH,
args: CatArgs {
mod_hash: CAT_PUZZLE_HASH.into(),
tail_program_hash: CurriedProgram {
program: GENESIS_BY_COIN_ID_TAIL_PUZZLE_HASH,
args: GenesisByCoinIdTailArgs {
genesis_coin_id: Bytes32::default(),
},
}
.tree_hash()
.into(),
inner_puzzle: CurriedProgram {
program: STANDARD_PUZZLE_HASH,
args: StandardArgs {
synthetic_key: PublicKey::default(),
},
},
},
}
.tree_hash();
```
=> Add TreeHasher to simplify currying puzzle hashes

Cargo.lock, wasm/Cargo.toml
Resolves the following warning about `wasm-bindgen`:
```
warning: the following packages contain code that will be rejected by a future version of Rust: wasm-bindgen v0.2.87
note: 
To solve this problem, you can try the following approaches:
- Some affected dependencies have newer versions available.
You may want to consider updating them to a newer version to see if the issue has been fixed.
wasm-bindgen v0.2.87 has the following newer versions available: 0.2.89, 0.2.90, 0.2.91, 0.2.92
- If the issue is not solved by updating the dependencies, a fix has to be
implemented by those dependencies. You can help with that by notifying the
maintainers of this problem (e.g. by creating a bug report) or by proposing a
fix to the maintainers (e.g. by creating a pull request):
- wasm-bindgen@0.2.87 …
```
=> Bump wasm-bindgen to 0.2.92

Cargo.lock, Cargo.toml
We will need to ideally update `clvmr` to use the new `chia-bls` version, then bump `clvmr` in `chia_rs`.
But I think in the lockfile, it's already replaced it since it's a semver compatible version.
=> Bump BLST to 0.3.12 and remove patch

crates/chia-bls/src/cached_bls.rs, crates/chia-consensus/benches/run-generator.rs, crates/chia-consensus/fuzz/fuzz_targets/fast-forward.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-conditions.rs, crates/chia-consensus/fuzz/fuzz_targets/parse-spends.rs, crates/chia-consensus/fuzz/fuzz_targets/process-spend.rs, crates/chia-consensus/fuzz/fuzz_targets/run-generator.rs, crates/chia-consensus/fuzz/fuzz_targets/run-puzzle.rs, crates/chia-consensus/src/consensus_constants.rs, crates/chia-consensus/src/fast_forward.rs, crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/run_block_generator.rs, crates/chia-consensus/src/gen/run_puzzle.rs, crates/chia-consensus/src/gen/test_generators.rs, crates/chia-tools/src/bin/analyze-chain.rs, crates/chia-tools/src/bin/test-block-generators.rs, tests/run_gen.py, tests/test_run_block_generator.py, tests/test_run_puzzle.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi, wheel/src/api.rs, wheel/src/run_generator.rs
as part of the condition parsing.
The message of `AGG_SIG_UNSAFE` conditions are not allowed to end with any of the suffixes used by `AGG_SIG_*` conditions (those suffixes are derived from `ADDITIONAL_DATA`, i.e. a unique identifier for the network).
This is currently validated in `pkm_pairs()` in `chia-blockchain`. This PR moves this validation into the condition parsing, to reject invalid conditions earlier. This requires `ConsensusConstants` to be passed in to run_block_generator and run_puzzle.
In `chia-blockchain`, the suffixes for the `AGG_SIG_*` conditions are computed on-the-fly. This patch also move the agg_sig_*_additional_data into ConsensusConstants instead.
=> Validate AGG_SIG_UNSAFE messages to not end in one of the banned suffixes

wheel/Cargo.toml
Just forgot to remove these earlier. Doesn't cause any problems, but it's redundant
=> Remove path in wheel dependencies

.github/workflows/benchmark.yml, .github/workflows/build-test.yml, pytest.ini
CI runtime:
| CI job | before | after | after / before |
| --- | --- | --- | --- |
| Continue with coverage | [6m 9s](https://github.com/Chia-Network/chia_rs/actions/runs/9550232150/job/26321721410) | [4m 18s](https://github.com/Chia-Network/chia_rs/actions/runs/9561446642/job/26355701139?pr=580) | 70% |
| python tests | [2m 59s](https://github.com/Chia-Network/chia_rs/actions/runs/9550232143/job/26321707824) | [1m 35s](https://github.com/Chia-Network/chia_rs/actions/runs/9561446637/job/26355691707?pr=580) | 53% |
=> run pytests in parallel

crates/chia-tools/graph.gnuplot, crates/chia-tools/parse-analyze-chain.py, crates/chia-tools/src/bin/analyze-chain.rs, crates/chia-tools/src/bin/test-block-generators.rs
The main change is to make `analyze-chain` use `run_block_generator()` and to also make `test-block-generators` correctly switch to `run_block_generator2()` at the hard fork block height.
Since `analyze-chain` is changed to use `run_block_generator()` instead of `run_program_with_counters()` it can no longer collect operator- and stack size counters. The output is changed and the log parser scripts are updated to account for this.
Example output from `analyze-chain`:
=> [CHIA-786] Update tools to work with the hard-fork

Cargo.toml, crates/chia-bls/src/bls_cache.rs, crates/chia-bls/src/gtelement.rs, crates/chia-bls/src/public_key.rs, crates/chia-bls/src/secret_key.rs, crates/chia-bls/src/signature.rs
There is a bug in `pyo3` (or at least, it seems like a bug), that prevents methods defined in `pymethods` from being visible to Python if they are defined within a different module (with a `#[cfg(feature = "py-bindings")]`, notably).
=> Fix pymethods by moving outside of pybindings modules

wheel/Cargo.toml, wheel/pyproject.toml
I made this because it allows me to specify a specific commit to install `chia_rs` from with pip.  Without this entry, the stub file doesn't come along and mypy doesn't function properly.  The `chia-blockchain` CI has some difficulties with this but I think that's because it is manually building it when installing from the commit rather than installing from a published version.  I'm not entirely sure how to check that though so some input on how reasonable this seems would be appreciated.
=> Add python source to `Cargo.toml`

crates/chia-bls/benches/cache.rs, crates/chia-bls/src/bls_cache.rs
to take an iterator of pairs rather than two separate iterators.
This allows for interleaving work in an iterator, which isn't possible with *two* iterators
=> update BLSCache::aggregate_verify() function signature

crates/chia-bls/src/gtelement.rs, tests/test_blspy_fidelity.py
make GTElement also use parse_hex_string (just like PublicKey, Signature and PrivateKey).
Add test cases to python tests.
=> test coverage for `parse_hex_string()`

crates/chia-consensus/src/gen/mod.rs, crates/chia-consensus/src/gen/test_generators.rs, crates/chia-consensus/src/spendbundle_conditions.rs, wheel/src/api.rs
and make `get_conditions_from_spendbundle()` return a non-owned `SpendBundleConditions` to enable reusing existing test facilities.
=> Extend the tests to cover the block-generator test cases

crates/chia-consensus/src/gen/get_puzzle_and_solution.rs
this is best reviewed with whitespaces ignored. 
https://github.com/Chia-Network/chia_rs/pull/642/files?diff=split&w=1
=> move tests into a test module in get_puzzle_and_solution_for_coin.rs

crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/get_puzzle_and_solution.rs
This patch deletes one of them.
=> we have two copies of the u64_to_bytes() function (used in tests)

.github/workflows/build-test.yml
My suspicion is that running pytest in parallel causes one process to overwrite the other's coverage report
=> fix the test coverage collected by pytest

.gitignore, .pre-commit-config.yaml
it makes `prettier` scan the whole repository.
Instead, rely on `pre-commit` to pass in the relevant files.
Also extend `.gitignore` to include the fuzz corpus
=> don't pass in the root directory to prettier (unconditionally) 

crates/chia-puzzles/src/puzzles/did.rs
If the recovery list is empty, this saves 32 bytes of space in the puzzle reveal.
=> CHIA-1171: Make DID recovery list hash optional

crates/chia-consensus/src/spendbundle_conditions.rs, crates/chia-consensus/src/spendbundle_validation.rs
the byte cost was not included in the returned cost field, but it's supposed to be
=> include byte cost in return value from `get_conditions_from_spendbundle()`

mypy.ini
This should probably be a lot more strict, but let's take that on separately.
https://github.com/Chia-Network/chia_rs/actions/runs/10581623686/job/29319386862?pr=673#step:10:16
```
mypy.ini: No [mypy] section in config file
```
=> add empty `[mypy]` section to avoid a warning

wheel/generate_type_stubs.py
```python-console
>>> f"\n{'\n'}"
'\n\n'
>>> len(f"\n{'\n'}")
2
```
=> remove incorrect comment and unused newline variable

crates/chia-consensus/src/gen/make_aggsig_final_message.rs, crates/chia-consensus/src/spendbundle_validation.rs
Reduce Vec allocations in `validate_clvm_and_signature()` by clearing and re-using the same Vecs
=> Optimize `make_aggsig_final_message()`

.pre-commit-config.yaml
Building and benchmarking the whole workspace takes a while and I'm not sure it's that necessary given that we have CI.
=> Remove bench and build from pre-commit

crates/chia-consensus/src/spendbundle_conditions.rs, crates/chia-consensus/src/spendbundle_validation.rs
The generator doesn't just include the puzzle reveal and the solution, it also includes the coin that's being spent, specifically in the form of `(parent_id, puzzle_hash, amount)`. Each spend will necessarily have to pay that size-cost.
=> CHIA-1226 Include the cost of the whole spend in get_conditions_from_spendbundle's return value

crates/chia-puzzles/src/puzzles/cat.rs, crates/chia-puzzles/src/puzzles/did.rs, crates/chia-puzzles/src/puzzles/nft.rs, crates/chia-puzzles/src/puzzles/singleton.rs, crates/chia-puzzles/src/puzzles/standard.rs, crates/clvm-derive/src/from_clvm.rs, crates/clvm-derive/src/parser/attributes.rs, crates/clvm-derive/src/to_clvm.rs, crates/clvm-traits/docs/derive_macros.md, crates/clvm-traits/src/lib.rs
When parsing CLVM solutions currently, the nil terminator is strict since they are represented as a normal list. This is fine if the solution is structured correctly, but as seen in https://github.com/Chia-Network/chia-blockchain/pull/18500, this is not always the case. I had an NFT which failed to parse due to this mistake of including the coin amount in the NFT state layer solution.
Instead of requiring the solution's terminator (which here refers to the last CLVM pair's "rest" value after extracting all of the required values in the list) to be nil, it can be any value and is not checked. This is achieved by adding a new representation `solution` which is identical to `list` except with this extra bit of flexibility. When serialized, it still includes the nil terminator as it should. …
=> Add a less strict solution representation

crates/chia-consensus/src/spendbundle_conditions.rs
```rust
altendky@p1 ~/r/chia_rs (main)> cargo clippy --workspace --all-features --all-targets
warning: adding items after statements is confusing, since items exist from the start of the scope
--> crates/chia-consensus/src/spendbundle_conditions.rs:43:5
|
43 |     const QUOTE_BYTES: usize = 2;
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#items_after_statements
= note: `-W clippy::items-after-statements` implied by `-W clippy::pedantic`
= help: to override `-W clippy::pedantic` add `#[allow(clippy::items_after_statements)]`
warning: `chia-consensus` (lib) generated 1 warning
warning: adding items after statements is confusing, since items exist from the start of the scope
--> …
```
=> fixup clippy warnings

crates/chia-consensus/src/spendbundle_conditions.rs
This is part of PR #703 that got conflicted by PR #705.
=> Revert accidental change while fixing clippy warnings

wheel/src/run_generator.rs
allowing these to be run in a `ThreadPoolExecutor`.
This PR is best reviewed ignoring whitespaces.
=> release the GIL in run_block_generator() and run_block_generator2()

crates/chia-consensus/benches/run-generator.rs, crates/chia-consensus/fuzz/fuzz_targets/run-generator.rs, crates/chia-consensus/src/gen/flags.rs, crates/chia-consensus/src/gen/get_puzzle_and_solution.rs, crates/chia-consensus/src/gen/run_block_generator.rs, crates/chia-consensus/src/gen/test_generators.rs, crates/chia-consensus/src/spendbundle_conditions.rs, crates/chia-tools/src/bin/analyze-chain.rs, crates/chia-tools/src/bin/test-block-generators.rs, wheel/src/api.rs, wheel/src/run_generator.rs
now that the mempool TX validation path has been separated from the block validation, we can remove the `ANALYZE_SPENDS` flag. It's implied for `validate_clvm_and_signature()`.
This, further, lets us remove the `SpendVisitor` generic parameter to `run_block_generator()` and `run_block_generator2()`.
With this PR https://github.com/Chia-Network/chia-blockchain/pull/18557 we have separated the mempool TX validation path from the block validation path. This is why we can now further simplify the block validation path.
=> [CHIA-1087] remove the `ANALYZE_SPENDS` flag

crates/chia-consensus/fuzz/Cargo.toml, crates/chia-consensus/fuzz/fuzz_targets/solution-generator.rs, crates/chia-consensus/src/gen/solution_generator.rs, crates/chia-consensus/src/spendbundle_conditions.rs
Adds a new function called `calculate_generator_length()` which deterministically calculates the generators byte length given the spends. This function can act as a drop in replacement when we only care about the size of the generator, as the input is the same.
=> Optimize `get_conditions_from_spendbundle()` by calculating the generator's size without creating the generator

README.md, crates/chia-tools/src/bin/gen-corpus.rs
the main feature is to generate corpus for the new solution-generator fuzzer, but also improves the generator to make other generators be disabled by default.
=> update gen-corpus to generate coin spends for solution-generator fuzzer

crates/chia-consensus/src/gen/solution_generator.rs
address comments from https://github.com/Chia-Network/chia_rs/pull/714
=> add test for `clvm_bytes_len()`

.github/workflows/benchmark.yml, mypy.ini
while latest clvm is indeed hinted, we aren't using latest clvm since we use old blockchain.  so, kinda reverting https://github.com/Chia-Network/chia_rs/pull/684.  the brokenness was masked by the universal `--ignore-missing-imports` on the cli in the ci runs.
=> move mypy config into config

crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/flags.rs, crates/chia-consensus/src/gen/get_puzzle_and_solution.rs, crates/chia-consensus/src/gen/make_aggsig_final_message.rs, crates/chia-consensus/src/gen/run_block_generator.rs, crates/chia-consensus/src/spendbundle_conditions.rs, crates/chia-consensus/src/spendbundle_validation.rs
There's nothing in `validate_conditions()` that need to take ownership of anything in `ParseState`.
Also, remove redundant `u64_to_bytes()` function and improve documentation of condition flags,
=> pass `ParseState` by reference into `validate_conditions()`

crates/chia-tools/src/bin/gen-corpus.rs
extend the `gen-corpus` tool to pull all block generators from a blockchain file and place them in the `run-generator` corpus directory.
It also avoid the cost of actually executing the generators unless it needs to because another corpus is being populated. The patch is best viewed with white space ignored.
=> update gen-corpus to save block generators

crates/chia-bls/src/bls_cache.rs, crates/chia-consensus/src/spendbundle_validation.rs
This reduces the allocations required inside the bls_cache and inside `spendbundle_validation.rs`.
=> Change BLSCache to use the augmented message for its lookup

crates/chia-bls/Cargo.toml, crates/chia-bls/src/bls_cache.rs
Make the `BlsCache` thread safe by making its cache be held by a `Mutex`.
This adds a small (0-6%) slow-down. It will allow `UnfinishedBlock`s to be validated in a thread pool, rather than the main thread, so that seems like a small price.
```
group                                          main.benchmark                         sync-cache.benchmark
-----                                          --------------                         --------------------
bls_cache.aggregate_verify, 0% cache hits      1.00    654.0±8.63ms        ? ?/sec    1.02   664.0±26.99ms        ? ?/sec
bls_cache.aggregate_verify, 10% cache hits     1.00   590.9±22.85ms        ? ?/sec    1.01    594.5±4.98ms        ? ?/sec
bls_cache.aggregate_verify, 100% cache hits    1.00      2.6±0.01ms        ? ?/sec    1.03 …
```
=> make BlsCache thread safe by adding an internal mutex

crates/chia-consensus/benches/run-generator.rs, crates/chia-consensus/fuzz/Cargo.toml, crates/chia-consensus/fuzz/fuzz_targets/additions-and-removals.rs, crates/chia-consensus/src/gen/additions_and_removals.rs, crates/chia-consensus/src/gen/mod.rs, crates/chia-tools/src/bin/gen-corpus.rs, tests/test_additions_and_removals.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi, wheel/src/api.rs, wheel/src/run_generator.rs
This adds a function called `additions_and_removals()`, which is similar to `run_block_generator()` and `run_block_generator2()` but with some important differences.
`additions_and_removals()`:
* assumes that the block is valid. It's only meant to be run on blocks we've already validated (and perhaps pulled out of the blockchain database).
* only return the created coins ("additions") and spent coins ("removals"). The created coins also include the optional hint.
The two main reasons to introduce this function are:
* It's faster than `run_block_generator()`
* It completes the two use cases `chia-blockchain` has for running blocks. Letting `run_block_generator()` be more specialized to always fully validate blocks (e.g. the signature).
In `chia-blockchain` we sometimes validate blocks …
=> [CHIA-1563] add function to run a *trusted* block and return additions and removals.

.github/workflows/build-wheels.yml, Cargo.lock, wheel/Cargo.toml
Add in some missing bits in wheel/Cargo.toml and some hacks around missing parts in the tar archive
Main items are:
needing to add in `chia-client` and `chia-ssl` to `wheel/Cargo.toml`
needing to remove the `../LICENSE` from `wheel/Cargo.toml` - this resulted in the tar not having the LICENSE file but also pip expecting it, so I just removed it for now.
I noticed the tar was missing the `src` directory, so I had to manually add in the src directory to the tar archive. 
This does make a` tar.gz` that does build on my riscv machine and also my mac.
=> Add needed items for sdist

Cargo.toml
For sooommeee reason :roll_eyes: dependabot likes to remove these from `Cargo.lock`.  As a stop gap, this PR adds them explicitly to the workspace in hopes of making dependabot useful again.  See https://github.com/Chia-Network/chia_rs/pull/762/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87e for example.
=> add fuzz packages to workspace

Cargo.lock, crates/chia-consensus/src/consensus_constants.rs, crates/chia-tools/Cargo.toml, crates/chia-tools/src/bin/analyze-chain.rs, crates/chia-tools/src/bin/gen-corpus.rs, crates/chia-tools/src/bin/test-block-generators.rs, crates/chia-tools/src/bin/validate-blockchain-db.rs, crates/chia-tools/src/visit_spends.rs
add tool to validate some aspects of a blockchain database file. Most importantly, that the coin set is consistent with all the blocks.
To use this program:
```
cd crates/chia-tools
cargo run --release --bin validate-blockchain-db -- ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
cargo run --release --bin validate-blockchain-db -- ~/.chia/mainnet/db/blockchain_v2_testnet11.sqlite --testnet
```
=> start a tool to validate aspects of the blockchain database

crates/chia-bls/benches/cache.rs, crates/chia-bls/src/bls_cache.rs, crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/run_block_generator.rs, wheel/src/run_generator.rs
`BLSCache` has all its members protected by a mutex. In order to allow threads sharing the same object, it needs to be treated as immutable. This is the patter `Mutex` is meant to be used in.
It's believed to address the issue from pyo3:
```
full_node chia.full_node.full_node: ERROR    Error in _handle_one_transaction, closing: Traceback (most recent call last):
File "/home/arvid/dev/chia-blockchain/chia/full_node/full_node.py", line 475, in _handle_one_transaction
inc_status, err = await self.add_transaction(entry.transaction, entry.spend_name, peer, entry.test)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/arvid/dev/chia-blockchain/chia/full_node/full_node.py", line 2681, in add_transaction
cost_result = await …
```
=> CHIA-1763: Make functions use bls cache immutably

Cargo.lock, crates/chia-bls/benches/cache.rs, crates/chia-bls/src/bls_cache.rs, crates/chia-protocol/src/bytes.rs, crates/chia-protocol/src/coin.rs, tests/test_coin.py, tests/test_program.py, wheel/Cargo.toml, wheel/src/api.rs
make sure Coin.name(), tree_hash() and Program.get_tree_hash() return bytes32 objects to python. This is tested by them printing as hex
=> fixed `bytes32` return values in py-bindings

Cargo.lock, crates/chia-puzzles/Cargo.toml, crates/chia-puzzles/src/puzzles/offer.rs
Fixes a bug where empty memo lists were treated the same as not having a memo list at all, which makes the announcement message different when fulfilling requested payments.
=> Fix memo parsing for offers

crates/chia-tools/src/bin/validate-blockchain-db.rs
extends the `validate-blockchain-db` tool with more checks. Specifically:
* the peak hash
* (optional) `height-to-hash`
=> Validate blockchain

crates/chia-tools/src/bin/validate-blockchain-db.rs
to print and continue rather than aborting, on errors
=> update the blockchain db validation tool

crates/chia-tools/Cargo.toml, crates/chia-tools/src/bin/rollback-blockchain-db.rs
if `--rollback` is not specified, prints the peak height and hash.
If `--rollback` is specified with a height lower than the current peak, the database is updated like this:
* the peak is updated to point to the block at the specified height
* all blocks with a height greater than the new peak are marked as `in_main_chain=0`
* all coins *created* after the new peak are deleted from the `coin_records` table
* all coins *spent* after the new peak are marked as unspent
Example use:
```
cargo run --release --bin rollback-blockchain-db -- --rollback 6255740 ~/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
```
Example output:
```
opening blockchain database file: /home/arvid/.chia/mainnet/db/blockchain_v2_mainnet.sqlite
peak height: 6267502
peak hash: …
```
=> [CHIA-1927] add tool to roll-back a blockchain database file to a previous height

.github/workflows/build-crate.yml, crates/chia-consensus/src/spendbundle_validation.rs
A while back I loosened the CI a bit to allow warnings through, and differentiated some of the warnings as hard errors. I think this is great for during development so you aren't forced to fix every strict clippy warning immediately, but when you're merging a PR through I think all of the warnings should be fixed beforehand. So I re-added the check in CI to deny warnings, while leaving it alone in precommit.
Another reason for allowing them before was that new nightly Rust versions would break CI without us changing the code. Now that we both use stable, and use a rust-toolchain.toml file, this is theoretically impossible.
=> Fix clippy warning and deny them in the future

wheel/pyproject.toml
https://github.com/Chia-Network/chia_rs/actions/runs/12574101581/job/35047783400?pr=836
```
⚠️  Warning: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
🍹 Building a mixed python/rust project
🔗 Found pyo3 bindings
🐍 Found CPython 3.10 at /home/ubuntu/actions-runner/_work/chia_rs/chia_rs/venv/bin/python
📡 Using build options features, bindings from pyproject.toml
⚠️  Warning: `project.version` field is required in pyproject.toml unless it is present in the `project.dynamic` list
💥 maturin failed
Caused by: Cannot build without valid version information. You need to specify either `project.version` or `project.dynamic = ["version"]` in pyproject.toml.
```
https://github.com/PyO3/maturin/blob/main/Changelog.md#180 …
=> fixup version for maturin

.github/workflows/build-wheels.yml, Cargo.lock, Cargo.toml, crates/chia-consensus/src/gen/solution_generator.rs
one important change to the way we serialize compressed CLVM (in `clvm_rs`) was that nodes whose serialized length is less than 4 bytes are not considered for deduplication, even though we might save 1 byte by doing so. This was a performance trade-off, as each lookup for a back-reference is quite expensive.
This is what causes the serialized output to change in one of the tests.
`cargo test` was failing to find openssl (the `openssl-sys` crate was failing). The fix is taken from https://github.com/sfackler/rust-openssl/issues/1542#issuecomment-1399358351
it adds 6 minutes to the job on windows.
It's unclear why this started failing now. But on CI we build with `--all-features`, which enables the `openssl` feature for windows. When we build the wheels, we use openssl for Linux and MacOS, …
=> bump clvm_rs dependency

.gitattributes
https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
default to showing lock file diffs in pr view.  they are defaulted to not showing since people often like to ignore their noise.  with granular changes i think it's worth looking over them to make sure there aren't unexpected changes.  in the case of merging large branches with too many lock changes to review, go ahead and mark it viewed and github will keep it hidden until it is changed.
like https://github.com/Chia-Network/chia-blockchain/pull/18939
=> **/*.lock  linguist-generated=false

.github/workflows/benchmark.yml, .github/workflows/build-wheels.yml, wheel/Cargo.toml
and enable it for non-windows builds.
I encountered this issue: https://stackoverflow.com/questions/70464585/error-when-installing-openssl-3-0-1-cant-locate-ipc-cmd-pm-in-inc
The new openssl build step requires a new perl package which needed to be installed on the docker image.
It appears the `--features` switch to `maturin` does not *add* features to what it find in `pyproject.toml`, but replaces them. That's why I had to also include `pyo3/extension-module` as a feature on the command line.
=> add the openssl feature to the chia_rs wheel

.github/workflows/benchmark.yml, .github/workflows/build-wheels.yml, Cargo.lock, Cargo.toml, crates/chia-consensus/src/gen/solution_generator.rs
This version fixes an issue in incremental serialization in version 0.11.0.
The full changelog since 0.10.0: https://github.com/Chia-Network/clvm_rs/compare/0.10.0...0.12.0
=> clvmr to 0.12.0

crates/chia-consensus/fuzz/fuzz_targets/run-generator.rs, crates/chia-consensus/src/gen/conditions.rs, crates/chia-consensus/src/gen/owned_conditions.rs, crates/chia-consensus/src/gen/run_block_generator.rs, crates/chia-consensus/src/spendbundle_conditions.rs, tests/test_run_block_generator.py, tests/test_streamable.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi
into `execution_time` and `condition_time` (as well as the existing total cost).
This is part of preparations for incrementally serialize compressed block generators. The cost we use for mempool items can't include the byte-cost, since it's only known as we're building the block. So this gives us access to the cost broken up into its components
=> extend `SpendBundleConditions` with the cost broken out

crates/chia-bls/Cargo.toml
https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies
Looks like it was implicit until Rust 1.60 which is when they introduced the `dep:` syntax
(thanks @Rigidity)
=> update chia-bls adding `dep:` to `dep:chia_py_streamable_macro`

crates/chia_py_streamable_macro/src/lib.rs
was missed with the other conversions for the update to pyo3 0.23+
=> update `PyStreamable` to provide `IntoPyObject()`

wheel/stubtest.allowlist.3-11-plus
https://github.com/Chia-Network/chia_rs/actions/runs/13160210820/job/36726792631#step:12:32
```
chia_rs.sized_byte_class.TypeVar.__init__ is inconsistent, stub does not have argument "name"
chia_rs.sized_byte_class.TypeVar.__init__ is inconsistent, stub does not have *args argument "constraints"
chia_rs.sized_byte_class.TypeVar.__init__ is inconsistent, stub does not have argument "bound"
chia_rs.sized_byte_class.TypeVar.__init__ is inconsistent, stub does not have argument "contravariant"
chia_rs.sized_byte_class.TypeVar.__init__ is inconsistent, stub does not have argument "covariant"
chia_rs.struct_stream.TypeVar.__init__ is inconsistent, stub does not have argument "name"
chia_rs.struct_stream.TypeVar.__init__ is inconsistent, stub does not have *args argument "constraints" …
```
=> fixup stubtest for mypy 0.15.0

crates/chia_py_streamable_macro/src/lib.rs, wheel/stubtest.allowlist.3-11-plus
Source hash: fd65c4feb6e5131f4916bf25f7637f99b81a1c02
=> catchup: into long_lived/initial_datalayer from main  @ fd65c4feb6e5131f4916bf25f7637f99b81a1c02

crates/chia-consensus/src/gen/conditions.rs
For a coin to be eligible for dedup it must reserve more value than its amount. `CREATE_COIN` and `RESERVE_FEE` are ways of reserving value.
=> Prevent dedup with excess amount

crates/chia-protocol/src/proof_of_space.rs, tests/test_proof_of_space.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi
repurpose the most significant bit in the `size` field of `ProofOfSpace` to indicate version 1 or 2 of the plot format.
=> update ProofOfSpace to support the new plot format

crates/chia-tools/src/bin/benchmark-condition-costs.rs
The benchmark was failing because `MEMPOOL_MODE` doesn't allow unknown conditions
=> fix codition benchmark to run in consensus mode

crates/chia-protocol/src/proof_of_space.rs, crates/chia_streamable_macro/src/lib.rs
renaming the field `size` -> `version_and_size` was important to make sure source code referring to this field is updated to handle the change in semantics. However, in order to stay backwards compatible with the RPC protocol, the field should still be called "size" in JSON dicts.
I've tested this change in `chia-blockchain` which has coverage of the JSON serialization of this type.
=> backwards compatibility

crates/chia-protocol/src/block_record.rs, crates/chia-protocol/src/pot_iterations.rs, tests/test_pot_iterations.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi, wheel/src/api.rs
* enable mypy on some test functions
* turn `signage_point_index` into a `u8`, like python.
* update python binding signatures to match the python implementation
=> [CHIA-2884] Pot iterations

.github/workflows/build-crate.yml, .github/workflows/build-wheels.yml, rust-toolchain.toml
they are not required to build and maturin presently installs them while building
also, while there is some other issue going on that would be nice to address separately, this does avoid the symptom of generator benchmarking builds failing on beast.
https://github.com/Chia-Network/chia_rs/actions/runs/15169429653/job/42655535606?pr=1051
```
💥 maturin failed
Caused by: Failed to run rustc to get the host target
Caused by: error from command -- stderr:
info: syncing channel updates for '1.85.0-x86_64-unknown-linux-gnu'
info: latest update on 2025-02-20, rust version 1.85.0 (4d91de4e4 2025-02-[17](https://github.com/Chia-Network/chia_rs/actions/runs/15169429653/job/42655535606?pr=1051#step:14:18))
info: downloading component 'clippy'
info: downloading component 'rustfmt'
info: installing …
```
=> remove components from `rust-toolchain.toml`

.github/workflows/benchmark.yml, Cargo.toml
to allow running `cargo bench --workspace`
=> disable benchmarks for root crate

crates/chia-consensus/benches/run-generator.rs, crates/chia-consensus/fuzz/fuzz_targets/additions-and-removals.rs, crates/chia-consensus/src/additions_and_removals.rs, tests/test_additions_and_removals.py, wheel/generate_type_stubs.py, wheel/python/chia_rs/chia_rs.pyi, wheel/src/run_generator.rs
We need the coin ID of the coin we're spending, and currently we comput it twice. Once in this function and once in the caller (on the python side). This saves one coin ID calculation per spend.
Also fix the benchmark for `run_block_generator2()` to not validate signatures. That's not what we're interested in benchmarking there.
=> make `additions_and_removals()` also return the coin-id of spends

crates/chia-consensus/src/run_block_generator.rs, crates/chia-consensus/src/spendbundle_conditions.rs, crates/chia-tools/src/visit_spends.rs
This PR identifies and removes the two places that use `extract_n()` outside of `run_block_generators()` and removes them in favour of `match_list!` and `destructure_list!`.
It also changes `extract_n` to be a private function to prevent people from using it again.
=> Remove extract_n() from external uses

crates/chia-consensus/src/opcodes.rs
Since the softfork that added the following conditions have activated and the feature flag has been removed to control them, the test for the feature flag is now pointless.
`SOFTFORK`
`AGG_SIG_PARENT`
`AGG_SIG_PUZZLE`
`AGG_SIG_AMOUNT`
`AGG_SIG_PUZZLE_AMOUNT`
`AGG_SIG_PARENT_AMOUNT`
`AGG_SIG_PARENT_PUZZLE`
`SEND_MESSAGE`
`RECEIVE_MESSAGE`
This should have been done in https://github.com/Chia-Network/chia_rs/pull/597
=> fix unit test for parse_opcode

crates/chia-tools/graph.gnuplot, crates/chia-tools/parse-analyze-chain.py, crates/chia-tools/src/bin/analyze-chain.rs
The indentation level is changed for a good portion of this patch. It's best viewed ignoring whitespace.
* run block generators in parallel
* don't validate signatures (to speed up analysis)
The log entries are no longer ordered by height, but gnuplot nor the parser cares.
=> parallelize `analyze-chain`
